### ISSUE TITLE
Project generated by suspenders doesnt work on aws elasticbeanstalk

### ISSUE THREAD

**Issue by replicat0r** [thoughtbot/suspenders#1008]
spent the past 2 days on this, I am not 100% sure why this happens, when deploying project generated by suspenders. The application deployed on elasticbeanstalk doesnt boot up correctly and, and it silently fails? I tried on cloudwatch and pull logs, it doesnt show any crash error, but neither does it boot. 

I have tested this with rails 6.0 ruby 2.6/2.5, on both phusion passenger and puma 2.6/2.5 of the elastic beanstalk. 

when deploy a vanilla rails 6 project to the exact same stack, the application works fine. I think possibly due to the puma config in cluster mode, I tried to copy and paste the vanilla config from rails 6, but that doesnt seem to work either. Neither honeybadger nor skylight reports any crash error when trying to reach the site, my assumption was that the application isnt even running after deployment. 

any idea on the possible causes?

**Comment by mike-burns** [comment]
When debugging AWS EB I've found that I need to SSH in and run `rails c` in order to get an error message out.

**Comment by composerinteralia** [comment]
Thank you for the issue! I'm going to close now since I am unsure what next steps we could take, and there hasn't been much activity on this issue lately. If this comes up again and there are specific things we can do within suspenders to fix the problem then we can reopen the issue.
