### ISSUE TITLE
bin/setup depends on FactoriesGenerator

### ISSUE THREAD

**Issue by jsilasbailey** [thoughtbot/suspenders#1039]
`bin/setup` requires the task `dev:prime` which is now provided by the `FactoriesGenerator`.

Setting up a project with `suspenders project-name` and then running `bin/setup` fails on the missing task.

**Comment by composerinteralia** [comment]
I just released suspenders 1.54.0, which had a lot of changes. I created a new application and ran `bin/setup` and it seems to have worked alright, so I am going to close this issue for now and assume it was fixed in 1.54.0. We can reopen if it comes up again.

**Comment by gaultierq** [comment]
the problem is still happening
