### ISSUE TITLE
The Oj gem is installed but not configured

### ISSUE THREAD

**Issue by georgebrock** [thoughtbot/suspenders#1049]
#923 introduced the Oj gem for fast JSON parsing and serialisation.

To [fully take advantage of Oj takes a bit more configuration][1], which Suspenders doesn't yet do for us.

I recently [added this Oj initialiser in a Suspenders-based app][2] and saw API response times decrease by ~8%:

```ruby
# config/initializers/oj.rb
require "oj"

Oj.optimize_rails
```

[1]: https://github.com/ohler55/oj/blob/develop/pages/Rails.md
[2]: https://github.com/thoughtbot/albaik-web/pull/830

**Comment by composerinteralia** [comment]
@georgebrock the link to the Oj initializer you used is not something I have access to. Are you able to post the code directly here?

**Comment by georgebrock** [comment]
@composerinteralia Oops, sorry about that. That project was in the thoughtbot GitHub org at the time of posting.

The most relevant bit is the `config/initializers/oj.rb` that's already in the original issue description; the rest of the PR is tweaking some tests that relied on a particular number of decimal places in serialised floating point numbers.
