### ISSUE TITLE
"trueconfig" error in config/environments/development.rb

### ISSUE THREAD

**Issue by dorianmariefr** [thoughtbot/suspenders#1053]
when generating a new project, `config/environments/development.rb` has:

```ruby
  config.active_storage.service = :local
  config.action_mailer.raise_delivery_errors = trueconfig.after_initialize do
  Bullet.enable = true
  Bullet.bullet_logger = true
  Bullet.rails_logger = true
end
  config.action_mailer.delivery_method = :file
```

error is:

```
undefined local variable or method `trueconfig' for #<Hivebrite::Application:0x00007febed6c92e8> (NameError)
```

i think a diff for the fix might be something like:

```diff
--- a/lib/suspenders/generators/db_optimizations_generator.rb
+++ b/lib/suspenders/generators/db_optimizations_generator.rb
@@ -11,7 +11,7 @@ module Suspenders
       inject_template_into_file(
         "config/environments/development.rb",
         "partials/db_optimizations_configuration.rb",
-        after: /config.action_mailer.raise_delivery_errors = .*/
+        after: /config.action_mailer.raise_delivery_errors = .*\n/m
       )
     end
   end
```

**Comment by composerinteralia** [comment]
Thanks for the report. What version of suspenders are you on? I was under the impression we had fixed this in https://github.com/thoughtbot/suspenders/commit/a8173cd767656c4a240edd9fd1d780f239789c54.

**Comment by kaka-ruto** [comment]
I just got the same error too. I am on suspenders `v1.55.0`

**Comment by kaka-ruto** [comment]
@composerinteralia, @dorianmariefr ,have a quick work around for this?

**Comment by composerinteralia** [comment]
The workaround for now is to manually go in and fix the spacing in the file (i.e. add a newline between `true` and `config`).

**Comment by kaka-ruto** [comment]
Thanks @composerinteralia . And then run `bin/setup` to continue installation? Sorry, it's my first time using suspenders :)

**Comment by composerinteralia** [comment]
Yeah, running bin/setup makes sense as a next step. Also, if any of the default generators failed you may need to re-run some of them. You can get the list of generators with `bin/rails generate | grep suspenders` and get more info about a specific generator with `bin/rails generate suspenders:<generator name> -h`

**Comment by kaka-ruto** [comment]
Thanks, yup, some of the generators failed. I'll follow along to find the failed generators, these will be helpful

**Comment by dorianmariefr** [comment]
@composerinteralia the whitespace is not in the file on master: https://github.com/thoughtbot/suspenders/blob/master/templates/partials/db_optimizations_configuration.rb (must have been removed somehow)

**Comment by dorianmariefr** [comment]
I built the gem with the whitespaces and now I'm getting:

```
config/boot.rb:4:in `require': cannot load such file -- bootsnap/setup (LoadError)
```
