### ISSUE TITLE
Replace `git` command in gemspec

### ISSUE THREAD

**Issue by utkarsh2102** [thoughtbot/suspenders#1055]
Hello @composerinteralia 👋🏻 

Thanks for your great work here and elsewhere! ❤️ 

Whilst maintaining this in Debian, I found that this library relies on `git` to produce a list of files.
https://github.com/thoughtbot/suspenders/blob/f16e7439f42acc508e297b32e79f551b11e995c2/suspenders.gemspec#L20

Using `git` in gemspec is a bit problematic and it's best if avoided. More about this can be found here:
https://docs.rubocop.org/rubocop-packaging/cops_packaging.html#gemspec-git-rationale

I'd be happy to submit a PR if you concur with this?

**Comment by composerinteralia** [comment]
Thanks for the kind words. Yeah, I'd be open to moving away from `git ls-file`. We use `Dir.glob` over on [factory_bot](https://github.com/thoughtbot/factory_bot/blob/master/factory_bot.gemspec#L13-L15), so I assume we could do something similar here.
