### ISSUE TITLE
Update for Rails 6.1.0

### ISSUE THREAD

**Issue by bmack123** [thoughtbot/suspenders#1060]
Suspenders currently locks rails to `~> 6.0.0` on the latest version. It would be nice if there was a new version that allowed users of suspenders to update to the latest version of Rails.

**Comment by stevepolitodesign** [comment]
@thiagoa made an excellent point: 

One way we could go about that is:

1. Generate a Suspenders application.
2. Upgrade it to Rails 6.1.0
3. Back port the changes to Suspender's source.

If we upgrade a Suspenders-generated app, we can easily take a look at the diff and then back port the changes.
