### ISSUE TITLE
Detect Ruby version in Gemfile

### ISSUE THREAD

**Issue by c4lliope** [thoughtbot/suspenders#1067]
This is an issue I experience whenever using suspenders;
the `Gemfile` specifies Ruby `2.6.3` or something similar,
so when I run the command with Ruby 3.0.1 on my machine
I see an error popping up endlessly during launch.

This has become such a problem that I am changing over
to a new base command for launching a rails program,
using the baked-in generator:
`rails new --webpack=react -T -d postgresql program_name`

...and I add in RSpec and additional layers as needed once done.

Is changing the Ruby version possible or desirable here?

**Comment by thiagoa** [comment]
@c4lliope Thank you for reporting this issue! 

I'm closing this ticket in favor of the following one: https://github.com/thoughtbot/suspenders/issues/1073
