### ISSUE TITLE
Make suspenders command smarter regarding the Ruby version

### ISSUE THREAD

**Issue by thiagoa** [thoughtbot/suspenders#1073]
If I run Suspenders with a Ruby version other than the one declared in `Gemfile`, I'm still able to generate my application but I get the following message over and over:

> Your Ruby version is X.X.X, but your Gemfile specified 2.6.6

 Here's some sample output:

```
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:advisories
       rails  generate suspenders:advisories
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:preloader
       rails  generate suspenders:preloader
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:staging:pull_requests
       rails  generate suspenders:staging:pull_requests
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:single_redirect
       rails  generate suspenders:production:single_redirect
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:compression
       rails  generate suspenders:production:compression
Your Ruby version is 2.7.2, but your Gemfile specified 2.6.6
    generate  suspenders:production:force_tls
```

There are some options to deal with this problem. The following ones crossed my mind:

1. Declare the minimum and maximum Ruby versions, and configure `Gemfile` with whatever version the user is using. If the user's version is less than the minimum or the maximum, fail before running anything.
2. Fail if the user's Ruby version is different than `Suspenders::RUBY_VERSION`

**Comment by thiagoa** [comment]
Personally, I think option 1 is less strict and more appropriate. With option 2, we are forcing the user to go with a particular Ruby version; for instance, if I `gem install suspenders` with a newer Ruby version, I would still get the same errors.

Declare a minimum Ruby version and letting the user choose which version they want to run may be more sensible. It's also worth noting that option 2 is harder to maintain because it requires constant updates to the codebase. 

That all said, there are some drawbacks to option 1. One of them is that we should not use any Ruby features not present in `MINIMUM_RUBY_VERSION`, and that would be something hard to put under test coverage.

**Comment by stevepolitodesign** [comment]
Just noting that after merging in #1087, we are no longer are able to generate a new app if the versions do not match. Instead, the script will abort.

![CleanShot 2023-01-13 at 14 23 26](https://user-images.githubusercontent.com/5122678/212404853-f0b527b3-f1c6-4fa4-a4ef-c4444e9b34f2.png)
