### ISSUE TITLE
Replace Delayed::Job with Sidekiq

### ISSUE THREAD

**Issue by thiagoa** [thoughtbot/suspenders#1074]
`Delayed::Job` was [a choice we made back in 2013](https://github.com/thoughtbot/suspenders/pull/166) and it made sense at the time.

Nowadays, Sidekiq is a more mature solution, and the argument of `Delayed::Job` not requiring a new dependency to run no longer makes sense because it's easy to add Redis to any platform, and not particularly expensive.

Sidekiq is not perfect, but it has better performance (scales better) and more momentum in the Ruby community.

Also, it's harder to switch from `Delayed::Job` to `Sidekiq` later on when in need of a full-featured solution.

**Comment by tuang3142** [comment]
@thiagoa may I grab this issue? I'd love to contribute

**Comment by thiagoa** [comment]
@tuang3142 Sure, please go ahead! Let me know if you have any questions.

**Comment by tuang3142** [comment]
@thiagoa it would be better if I have a deadline to work with.  Do 2 weeks sound good to you?

**Comment by thiagoa** [comment]
@tuang3142 It's your call, no pressure on our side 😉 If you think that would help you, go for it.

**Comment by thiagoa** [comment]
@tuang3142 Are you still interested in this issue?

**Comment by caiohsramos** [comment]
@thiagoa do you mind if I work on a PR for this one? If we keep the ActiveJob adapter, I think it will be pretty straightforward

**Comment by thiagoa** [comment]
@caiohsramos Not at all! Please go ahead and let me know if I can be of help somehow.
