### ISSUE TITLE
Do not use a custom Gemfile

### ISSUE THREAD

**Issue by thiagoa** [thoughtbot/suspenders#1082]
We should not use a custom `Gemfile` - we should use whatever `Gemfile` Rails generates for us. In practice, that approach results in inconsistencies like [specifying a different database and the gem for that database not being inserted into Suspender's `Gemfile`](https://github.com/thoughtbot/suspenders/issues/893) because Rails's Gemfile gets replaced.

Any differences regarding the `Gemfile` we want to achieve should be resolved with custom generators and/or other means.

This ticket will also be useful to aid in our [individual generator goal](https://github.com/thoughtbot/suspenders/blob/1473ca7a23937ce7af5e5acf610ed6d1ca1b87ff/GOALS.md).

**Comment by stevepolitodesign** [comment]
Closed by #1135
