### ISSUE TITLE
Update and review README

### ISSUE THREAD

**Issue by thiagoa** [thoughtbot/suspenders#1084]
Our README is out of date and not synced with the current state of the app. Among other things, we need to:

- Review each gem and instruction. Is the gem still present? Does the instruction still apply?
- What information do we need to _add_?
- [Suggestion: Include a basic section about how generators work or make a blog post and link to it. Briefly explain the generator hierarchy, which can be confusing to new contributors](https://github.com/thoughtbot/suspenders/issues/1025)
- Explicitly state our [GOALS](https://github.com/thoughtbot/suspenders/blob/a96628ba03cdb018c1ad69ac31be24d227854277/GOALS.md)

**Comment by stevepolitodesign** [comment]
Closed by #1135 and #1199
