### ISSUE TITLE
When not running PostgreSQL Suspenders fails to create the database but proceeds

### ISSUE THREAD

**Issue by thiagoa** [thoughtbot/suspenders#1086]
Since we're dealing with a legitimate failure, we should stop the program and document that somehow.

**Comment by stevepolitodesign** [comment]
This is closed by #1135. Specifically, we fail if the caller is not using PostgreSQL.

https://github.com/thoughtbot/suspenders/blob/efe875c0810902766b836acc93f9a80b97f685dc/lib/install/web.rb#L25
