### ISSUE TITLE
After scaffolding a model, one of the generated tests fails

### ISSUE THREAD

**Issue by dorianmariefr** [thoughtbot/suspenders#1090]
The generated scaffolded tests include controller specs which don't render views by default.

rspec-rails is not compatible with the rails 6.0 because of a wrong number of arguments

Solution:

Upgrade rspec-rails (will default to generate requests specs which render views)

**Comment by thiagoa** [comment]
Resolved in https://github.com/thoughtbot/suspenders/pull/1094
