### ISSUE TITLE
Running ./bin/setup fails to run

### ISSUE THREAD

**Issue by stevepolitodesign** [thoughtbot/suspenders#1095]
## Steps to reproduce

1. `$ suspenders name_of_app`
2. `$ cd name_of_app`
3. `$ ./bin/setup`

```
Database 'demo_app_development' already exists
Database 'demo_app_test' already exists
You have 1 pending migration:
  20220610190223 CreateDelayedJobs
Run `rails db:migrate` to update your database then try again.
```

**Comment by stevepolitodesign** [comment]
I think one solution is too add `bin/rails db:reset || bin/rails db:migrate` before `bin/rails dev:prime` in `templates/bin_setup`.

However, I'm noticing that we call `bundle exec rails db:create db:migrate` in `lib/suspenders/app_builder.rb`, which is called during the initial suspenders command.

I wonder if we need to run the generator that installs delayed job first?

**Comment by thiagoa** [comment]
@stevepolitodesign Yep, I think that makes sense. We could probably mix and match both solutions, as the first one (changing `bin/setup`) would also be useful for anyone cloning the project for the first time. What do you think?
