### ISSUE TITLE
Difference between documentation and reality

### ISSUE THREAD

**Issue by fuzzygroup** [thoughtbot/suspenders#1096]
Bug 1: It doesn't use the latest rails; just the latest rails the user has in their current ruby

You pretty clearly state in the readme that this builds an app with the latest version of rails.  It is actually the version of rails available to whatever ruby you have installed.  

Example - I installed 2.6.6 to run this (because of bug 2).  I then found out at the end that I was using Rails 6 not Rails 7.

Solution: change the documentation

Bug 2: If you have a ruby that isn't 2.6.6 you see errors like:

Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6

Solution: remove the ruby version from the gemfile and direct people to add it themselves (or add it yourself via bash at the end of the process)

Bug 3: If you use Ruby 3 then you never continue onto the asset compilation stuff / later steps.  It stops with:

Congratulations! You just pulled our suspenders.
Run 'bundle exec honeybadger heroku install' with your API key.
         run  bundle install
Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6
         run  bundle binstubs bundler
Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6
         run  bundle exec spring binstub --all
Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6
       rails  webpacker:install
Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6
    generate  suspenders:views
       rails  generate suspenders:views
Your Ruby version is 3.1.2, but your Gemfile specified 2.6.6

When it is running Ruby 2.6.6 and Rails 6 then it continues much, much longer.  At this point I don't even know what is the correct behavior.

However the byte size difference in the generated apps is considerable:

❯ du -hc cartazzi_home_rails7 | grep total
312K	total

❯ du -hc cartazzi_home_rails6 | grep total
156M	total

So I think that this really isn't working right on:

ruby -v
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin19]

and Rails 7

Bug 4:  Errors in un_bundled_env

And there is a lot of this in 2.6.6 install:

   generate  suspenders:profiler
       rails  generate suspenders:profiler
W, [2022-06-19T06:25:11.116230 #24247]  WARN -- Skylight: [SKYLIGHT] [5.3.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
      append  .sample.env
     gemfile  rack-mini-profiler
Traceback (most recent call last):
	19: from bin/rails:4:in `<main>'
	18: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	17: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	16: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/railties-6.0.5/lib/rails/commands.rb:18:in `<main>'
	15: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/railties-6.0.5/lib/rails/command.rb:46:in `invoke'
	14: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/railties-6.0.5/lib/rails/command/base.rb:69:in `perform'
	13: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	12: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	10: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/railties-6.0.5/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	 9: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/railties-6.0.5/lib/rails/generators.rb:276:in `invoke'
	 8: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	 7: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	 6: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	 5: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	 4: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	 3: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	 2: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	 1: from /Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/sjohnson/.rvm/gems/ruby-2.6.6/gems/suspenders-1.55.1/lib/suspenders/generators/profiler_generator.rb:19:in `add_gem': undefined method `with_unbundled_env' for Bundler:Module (NoMethodError)
Did you mean?  with_clean_env

**Comment by thiagoa** [comment]
@fuzzygroup Thank you for reporting this issue! Some of your complaints have been fixed with the latest release (UX improvements):

https://github.com/thoughtbot/suspenders/releases/tag/v1.56.0

Note that:

- Ruby and Rails haven't been upgraded yet. We're in the process of upgrading and modernizing Suspenders
- We're in the process of making Suspenders more flexible

The README will be eventually fixed when we make these improvements.

If you're still interested, please check out the latest version and let us know how it goes. I'm closing this issue but feel free to reopen it if you find anything outstanding.
