### ISSUE TITLE
Your Ruby version is 3.1.3, but your Gemfile specified 3.0.5

### ISSUE THREAD

**Issue by stevepolitodesign** [thoughtbot/suspenders#1118]
When running `suspenders app_name` on [this commit](https://github.com/thoughtbot/suspenders/commit/1712f3e9efa30e3e5f8270992eb2765791e59b7d), I get the following error:

```text
Your Ruby version is 3.1.3, but your Gemfile specified 3.0.5
```

This might relate to #1073, but requires further investigation, since we just updated our supported Ruby version.

**Comment by thiagoa** [comment]
@stevepolitodesign Is this issue a duplicate of:

https://github.com/thoughtbot/suspenders/issues/1073

**Comment by stevepolitodesign** [comment]
@thiagoa thank you for referencing that issue. I think this might be related, although in my case, the script fails to continue.

![CleanShot 2023-01-13 at 14 23 26](https://user-images.githubusercontent.com/5122678/212401779-295a6d81-3972-41a0-913e-953a8d44a81f.png)

**Comment by thiagoa** [comment]
@stevepolitodesign It's because Suspenders is now aborting:

https://github.com/thoughtbot/suspenders/pull/1087

When the issue was created, it didn't abort when a subprocess failed. However, the issue seems to be the same still. Thoughts on updating it?

**Comment by thiagoa** [comment]
Adding more context, the idea of that issue is to make the Ruby version more flexible. Suspenders forces us to run with the exact Ruby version declared here:

https://github.com/thoughtbot/suspenders/blob/main/.ruby-version

Which isn't great. That issue has a few thoughts on how we could fix the problem.

**Comment by stevepolitodesign** [comment]
@thiagoa ah, thank you for the additional context. I will close this in favor of the existing issues 👍 

Also, in case you're wondering why we settled on version `3.0.5` and not the latest version of Ruby, it's because


> We were unable to support the latest version of Ruby because of a [failing build](https://github.com/thoughtbot/suspenders/actions/runs/3418310707). A future commit could explore how to solve for this, but for now, we decided to just stick with version `3.0.5`. We settled on `3.0.5` and not `3.0.0` in an effort to suppress parser warnings.
