### ISSUE TITLE
Annotate HTML output with template file names by default

### ISSUE THREAD

**Issue by MatheusRich** [thoughtbot/suspenders#1120]
[Rails 6.1 added support] to annotating HTML output with template file names. This adds a comment to the rendered HTML with the file name of the view used to generate that particular template portion.

That is a very valuable tool during development.

[Rails 6.1 added support]: https://blog.saeloun.com/2020/05/11/rails-support-annotates-html-output-with-template-file-names.html

<img width="623" alt="image" src="https://user-images.githubusercontent.com/20938712/213266852-e5907692-b0b2-4019-a286-4bc7f2f944ce.png">

**Comment by stevepolitodesign** [comment]
I like this. Makes for a sensible default.

**Comment by MatheusRich** [comment]
[This is on by default in Rails main](https://github.com/rails/rails/pull/50436)

**Comment by stevepolitodesign** [comment]
@MatheusRich thank you for the update.

Closing this, but noting that #1149 may need to still implement this configuration since https://github.com/rails/rails/pull/50436 is not captured in the latest release of Rails.
