### ISSUE TITLE
Add lograge for smaller, cleaner logs

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#292]
https://github.com/roidrage/lograge

Advantages:
- Papertrail (or Loggly, etc) doesn't fill up with logs as fast, meaning we can stay on lower, cheaper tiers.
- Logs are nicer to look at and easier to parse.

Disadvantages:
- It's just possible that this has less information than the default logs, but I don't think so.

**Comment by delphaber** [comment]
Will you consider a PR on this?

**Comment by nickcharlton** [comment]
I don't think this is something we've broadly been doing, tbh, so probably not any time soon.
