### ISSUE TITLE
Remove SimpleCov in favor of CodeClimate

### ISSUE THREAD

**Issue by croaky** [thoughtbot/suspenders#313]
https://codeclimate.com/changelog/5313a93ce30ba060970056fb

**Comment by croaky** [comment]
SimpleCov was removed from Suspenders in June in 6ece3c4, partially due to that Travis bug that appears to be fixed now.

**Comment by bf4** [comment]
@croaky let me know if I can help re: simplecov in any way.

**Comment by tute** [comment]
Is there anything suspenders can do to easy the set up of SimpleCov with CC? Should we have SimpleCov compute coverage locally, anyway, however we run CI?

**Comment by jferris** [comment]
> Should we have SimpleCov compute coverage locally, anyway, however we run CI?

I think that would be the best solution. The project needs SimpleCov set up correctly to support Code Climate, so we may as well make it easy to see coverage locally. Code Climate just makes a convenient public report and notifier when it comes to coverage.

**Comment by bf4** [comment]
Check out the bin dir for how you can dump reports to the file system,
then send along, like on tddium

**Comment by tute** [comment]
Please see PR: https://github.com/thoughtbot/suspenders/pull/524.

**Comment by tute** [comment]
Closing in favor of PR.
