### ISSUE TITLE
Environment variables seem incomplete

### ISSUE THREAD

**Issue by lpender** [thoughtbot/suspenders#418]
```
suspenders app --heroku true
cd app
git push staging master
```

ends in

```
KeyError: key not found: "SMTP_ADDRESS"
```

Adding the following config vars makes the heroku deploy build pass:

```
SMTP_ADDRESS=
SMTP_DOMAIN=
SMTP_PASSWORD=
SMTP_USERNAME=
EMAIL_RECIPIENTS=
ASSETS_VERSION=
ASSET_HOST=
```

However, I'm still getting an application error from Heroku when visiting the page.

Thoughts?

**Comment by jkrmr** [comment]
This was helpful: https://github.com/thoughtbot/suspenders/pull/532#issuecomment-86976291

**Comment by shashankshandilyav** [comment]
Could someone guide me what should we do when we have this issue?
