### ISSUE TITLE
simple_form warning about missing configuration

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#452]
Running rspec spec/ a lot of Simple Form warnings appears. Actually it's the same warning repeated for each test.

````bash
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
.[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
.[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
````

Could it be a good idea to run `rails g simple_form:install` within suspenders? If yes, I could try to do a pr

**Comment by dmitriy-kiriyenko** [comment]
Not fixed btw – it displays warning on `generate rspec` and on the `generate simple_form:install` itself =)

**Comment by delphaber** [comment]
Yep I know :( 

It should be fixed when you `rails s` your suspenderized app, but running 'rspec spec/` within suspenders still print out a lot of warnings like this. Any help appreciated!

**Comment by mcmire** [comment]
You say "it prints out a lot of warnings like this", can you list some of the ones you're seeing?

**Comment by proletarian** [comment]
I get the warnings in the original description and no other warnings.

**Comment by mcmire** [comment]
I'll reopen this, then.

**Comment by tute** [comment]
One unnecessary warning is being worked on https://github.com/plataformatec/simple_form/issues/1316.
