### ISSUE TITLE
Pry Timeout 

### ISSUE THREAD

**Issue by EdwardReed** [thoughtbot/suspenders#455]
When using binding.pry in a post request unicorn will timeout ?

**Comment by croaky** [comment]
@EdwardReed I haven't run into this before.

Is this happening in a dev, test, staging, or production environment?

Do you have a backtrace?

**Comment by tute** [comment]
@EdwardReed is this still an issue for you? How can we replicate it?

**Comment by mcmire** [comment]
I've run into this before. This is a "known issue" with Unicorn because of its timeout. You can replicate it by placing a `binding.pry` in any controller action. Wait 10 seconds and in the Foreman log you should see the Unicorn worker getting killed and restarted.

If we switch to Puma, I believe this problem should go away.

**Comment by jferris** [comment]
> If we switch to Puma, I believe this problem should go away.

Have you tried this? Puma is multithreaded, and there are [known issues] with Pry and threads.

[known issues]: https://github.com/pry/pry/wiki/FAQ#readline_threads

**Comment by mcmire** [comment]
Ah, okay. I have not tried it myself, so I was not aware of this issue.

**Comment by pedrosmmoreira** [comment]
I can confirm this is the case with Puma on a Suspenders app running the proposed config in https://github.com/thoughtbot/suspenders/pull/501

**Comment by tute** [comment]
@pedrosmmoreira what is the case, it works or it presents thread issues? If it works, I'd close this issue in favor of #501.

**Comment by pedrosmmoreira** [comment]
@tute, I've tried reproducing this again and I believe the timeouts I am seeing are due to Rack::Timeout

**Comment by tute** [comment]
As of https://github.com/thoughtbot/suspenders/commit/a470912e9df01fda62f0c23ce032a1c9b5493b69 rack-timeout is only loaded in staging and production. Does that fix the issue?

**Comment by tute** [comment]
This should be fix as of linked commit. Closing for now.
