### ISSUE TITLE
Bourbon installation potentially out of date

### ISSUE THREAD

**Issue by whmii** [thoughtbot/suspenders#472]
A client of ours mentioned that they had used suspenders to initialize a product and it had given them a very old version of Bourbon. Suspenders should probably just pull in the latest release version, now that sass-rails isn't wicked out of date.

**Comment by croaky** [comment]
Addressed by https://github.com/thoughtbot/suspenders/pull/478

**Comment by whmii** [comment]
@kylefiedler many thanks
