### ISSUE TITLE
Refills flashes component is not found, causing app to crash

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#476]

**Comment by gabebw** [comment]
We include Bourbon's `extends/flashes` anyway.

**Comment by croaky** [comment]
Any idea what the fix would be? @kylefiedler When you run the following:

```
suspenders project
cd project
foreman start
```

Is there different Refills setup we should be using?

**Comment by kylefiedler** [comment]
The issue here is that the Refills gem isn't up to date with the Refills repo. @Magnus-G can we release a new version of the Refills gem?

@gabebw Bitters flashes are being removed.

**Comment by gylaz** [comment]
Experienced this today on `1.23.0` version. How do I proceed?

**Comment by Magnus-G** [comment]
@teoljungberg do you have time to look into this?

**Comment by teoljungberg** [comment]
We're planning on releasing 1.0.0 as soon as we can, @Magnus-G and I dug through the issues and pull-requests we currently have.

As as quickfix until we have released 1.0.0, maybe we should change the `Gemfile` to fetch from github instead of rubygems?

**Comment by croaky** [comment]
@teoljungberg @Magnus-G @kylefiedler We can point to GitHub if that's what you recommend but is there any reason not to release `0.0.3` or `0.1.0` of Refills?

https://github.com/thoughtbot/refills/blob/master/lib/refills/version.rb

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/

**Comment by teoljungberg** [comment]
@croaky we still have a few PRs to burn through. So for a quick fix I would point refills against github. I can open a PR with once the verion bump has happend.

**Comment by croaky** [comment]
@teoljungberg @Magnus-G @kylefiedler It appears that when using the `github:` option, Refills is not able to install due to an infinite loop in the Bundler resolver. Reported as https://github.com/thoughtbot/refills/issues/231

**Comment by derekprior** [comment]
@croaky not going to resolve your issue exactly, but don't use `github`. It will fail bundle audit because it uses the git protocol which is plain text and subject to MITM. If we're going to use a github source, we should use https.

**Comment by teoljungberg** [comment]
@croaky I just tried it out myself by using this diff in suspenders:
```diff
diff --git a/templates/Gemfile.erb b/templates/Gemfile.erb
index 0bd195b..4df9267 100644
--- a/templates/Gemfile.erb
+++ b/templates/Gemfile.erb
@@ -18,7 +18,7 @@ gem "pg"
 gem "rack-timeout"
 gem "rails", "<%= Suspenders::RAILS_VERSION %>"
 gem "recipient_interceptor"
-gem "refills"
+gem "refills", github: "thoughtbot/refills"
 gem "sass-rails", "~> 5.0"
 gem "simple_form"
 gem "title"
```
And that generated a new application for me without a hiccup. What bundler version are you on etc?

**Comment by croaky** [comment]
Bundler 1.7.12.

@derekprior Good call. I did notice that as well and tried a few different
variations (https, etc.) Also saw the same result when getting a fresh
clone of Refills and trying to bundle it.

**Comment by teoljungberg** [comment]
@croaky I bumped refills to `0.1.0` and we'll follow SEMVER as closely as we can from now on. Which should mean that this shouldn't be a problem anymore. Can anyone verify, @gabebw @gylaz ?

**Comment by croaky** [comment]
Thanks, @teoljungberg! Just tested this and everything looks good.
