### ISSUE TITLE
Inflections.rb  -  warning: ambiguous first argument; put parentheses or a space even after `/' operator

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/suspenders#480]
config/initializers/inflections.rb:19: warning: ambiguous first argument; put parentheses or a space even after `/' operator

**Comment by ACPK** [comment]
Evertime I run rake, I have to first clear the Heroku staging database or I get:

    rake aborted!
    PG::ConnectionBad: FATAL:  permission denied for database "postgres"
    DETAIL:  User does not have CONNECT privilege.
    -e:1:in `<main>'
    Tasks: TOP => db:test:load => db:test:purge
    (See full trace by running task with --trace)
    /Users/andrewcharleskelley/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/activerecord-4.2.0/lib/active_record/migration.rb:393:in `check_pending!':  (ActiveRecord::PendingMigrationError)

    Migrations are pending. To resolve this issue, run:

      bin/rake db:migrate RAILS_ENV=test

**Comment by gabebw** [comment]
Hmm, I don't see anything that we do with "inflections" in the source: https://github.com/thoughtbot/suspenders/search?utf8=%E2%9C%93&q=inflections

Can you paste the full contents of `inflections.rb`?

**Comment by croaky** [comment]
Yeah, Suspenders doesn't touch the `inflections.rb` file. A clean `suspenders` run generates the same as `rails new`, a completely commented-out file:

```ruby
# Be sure to restart your server when you modify this file.

# Add new inflection rules using the following format. Inflections
# are locale specific, and you may define rules for as many different
# locales as you wish. All of these examples are active by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.plural /^(ox)$/i, '\1en'
#   inflect.singular /^(ox)en/i, '\1'
#   inflect.irregular 'person', 'people'
#   inflect.uncountable %w( fish sheep )
# end

# These inflection rules are supported but not enabled by default:
# ActiveSupport::Inflector.inflections(:en) do |inflect|
#   inflect.acronym 'RESTful'
# end
```
