### ISSUE TITLE
Add a flag to turn off email

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#488]
When an app doesn't send email (which is often), I have to rip out recipient interceptor and `SMTP_SETTINGS`, otherwise the `ENV.fetch` in `SMTP_SETTINGS` crashes deploys on Heroku.

**Comment by croaky** [comment]
Agreed. I like this idea.

**Comment by gylaz** [comment]
Ran into Heroku deploy issue today, and wondered why `STMP_*` settings aren't in the `.sample.env` file, so I can at a glance see what config vars I need to pre-define on Heroku before trying to deploy.

**Comment by tute** [comment]
@gylaz `ASSET_HOST` seems to be needed in `.sample.env` too, probably there's an issue/PR waiting there.

Should we close this issue in favor of https://github.com/thoughtbot/suspenders/pull/511?

**Comment by croaky** [comment]
Sounds good to close in favor of #511.

**Comment by tute** [comment]
Closing in favor of #511.

**Comment by toobulkeh** [comment]
Any hints in .sample.env towards what these variables should be would help too!
I like the sendgrid hint, but being new to heroku too not sure if I should set the ASSET_HOST manually to the Heroku URL or just jump into a CDN.

Also, setting heroku variables was a pain. couldn't .env.staging be used for this? Maybe I'm just missing something. 'scuse my ignorance.

**Comment by jferris** [comment]
> Also, setting heroku variables was a pain. couldn't .env.staging be used for this? Maybe I'm just missing something. 'scuse my ignorance.

Storing the environment-specific configuration in environment variables is one of the tenants of Heroku.

Heroku says this in their [dev center](https://devcenter.heroku.com/articles/config-vars):

> The traditional approach for handling such config vars is to put them under source - in a properties file of some sort. This is an error-prone process, and is especially complicated for open source apps which often have to maintain separate (and private) branches with app-specific configurations.
>
> A better solution is to use environment variables, and keep the keys out of the code.

Practically, using `.env.staging` has the following disadvantages:

* You need to commit and deploy when changing any configuration.
* You'll need to store sensitive configuration (like passwords and API keys) in a Git repository.

Heroku has some more to say about config in their [Twelve-Factory App](http://12factor.net/config) essay.

**Comment by toobulkeh** [comment]
Fair enough jferris, that makes a lot of sense! Thanks for the intelligent writeup and sources!

**Comment by CDainMiller** [comment]
Wow, I had no idea Heroku authored that 12factor site. 

The things you learn following Thoughtbot repos. Love it :)

**Comment by estiens** [comment]
Can we get an answer about hints as to what these variables should be set to? Especially on heroku? Also there is a gem called [dotenv-heroku](https://github.com/sideshowcoder/dotenv-heroku) that allows you to push all you ENV variables from a .gitignored .env file that can be especially useful if you hav a bunch of them to set.

**Comment by gabebw** [comment]
I would set ASSET_HOST to the same thing you set HOST to initially: `whatever.herokuapp.com`. We don't recommend a CDN immediately unless there's an obvious need.
