### ISSUE TITLE
Heroku setup does not run in app's directory if apps already exist on Heroku

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#489]
When I run `suspenders -H shorthanded`, I get the following output:

```
         run   heroku config:add RACK_ENV=staging RAILS_ENV=staging --remote staging from "."
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
      append  bin/setup
         run   heroku config:add SECRET_KEY_BASE=efcbbd7e2038086f52b0323e5c3ac7515efc4ea4b5a6381f7dc142643ce16a9fd3926ae0d0530f8c4f7c5aea9b955c6d77cd9fbd5732368e1f909d549b6875ab --remote staging from "."
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
         run   heroku config:add SECRET_KEY_BASE=b4c97832a558a26405db99e11bb6dff906e1c2abbecd1ba7c10368d5114ee1b37b927116e0b2bc72f37b3b40c3dafc6a1b5529b74d7856ba564bb8c120f84022 --remote production from "."
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
         run   heroku config:add NEW_RELIC_AGGRESSIVE_KEEPALIVE=1 --remote staging from "."
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
         run   heroku config:add NEW_RELIC_AGGRESSIVE_KEEPALIVE=1 --remote production from "."
 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.
```

This suggests that `heroku` is running in the directory that I'm running `suspenders shorthanded` from, not the actual `shorthanded` directory.

**Comment by gabebw** [comment]
Hmm, running it in the app directory doesn't work either, same error. Looks like the Git remotes aren't being added **if the app already exists**:

```
$ cd shorthanded
$ git remote -v
$
```

**Comment by croaky** [comment]
Further up in the backlog, it says:

```
         run   heroku create shorthanded-production  --remote production from "."
 !    Name is already taken
         run   heroku create shorthanded-staging  --remote staging from "."
 !    Name is already taken
```

It's unfortunate that there's a lot of output before and after so these lines get buried. But, I think the error message from the `heroku` client is clear. From Suspenders' perspective, I'm thinking we shouldn't add extra code to guard against it, as the user can re-run the command with a different name.

**Comment by jferris** [comment]
I've seen a few cases (Heroku name being taken, gems failing to compile) where Suspenders fails somewhere and then attempts to continue. Should we try and get Suspenders to loudly fail and abort when something goes wrong?

**Comment by croaky** [comment]
Like set -e for Rails generators?

**Comment by jferris** [comment]
> Like set -e for Rails generators?

Exactly.
