### ISSUE TITLE
Comment out ASSET_HOST setting?

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#491]
I think this is good to have but is unlikely to be set up within the first, say, 2 months of a project's existence (if ever). Since suspenders' target audience is new projects, the following line crashes Heroku pretty consistently and project owners are unlikely to have something to set `ASSET_HOST` to:

```
config.action_controller.asset_host = ENV.fetch("ASSET_HOST")
```

Can we generate it but keep it commented? Thoughts?

**Comment by croaky** [comment]
I usually set it to HOST (staging.project.com) at first, then switch to a CDN at "prep for public launch" time.

**Comment by gabebw** [comment]
Ah, that makes sense. Maybe worth a comment above that line saying that?

**Comment by gabebw** [comment]
Oh, or even:

```ruby
= ENV.fetch("ASSET_HOST", ENV.fetch("HOST"))
```

**Comment by croaky** [comment]
Clever. I think I like it.

**Comment by tute** [comment]
If now we require `ASSET_HOST` for production, shouldn't it exist in `.sample.env` file?

I like `ENV.fetch("ASSET_HOST", ENV.fetch("HOST"))`.

**Comment by croaky** [comment]
> If now we require `ASSET_HOST` for production, shouldn't it exist in `.sample.env` file?

Yup, sound good.
