### ISSUE TITLE
Suspenders should fail and abort when a generator's action fails

### ISSUE THREAD

**Issue by croaky** [thoughtbot/suspenders#493]
From @jferris:

> I've seen a few cases (Heroku name being taken, gems failing to compile) where Suspenders fails somewhere and then attempts to continue. Should we try and get Suspenders to loudly fail and abort when something goes wrong?

**Comment by JoelQ** [comment]
:+1:

**Comment by tute** [comment]
I agree that it should abort if something goes wront.

I couldn't find documentation. Where can I find out more about `-e`?

**Comment by jferris** [comment]
http://stackoverflow.com/questions/19622198/what-does-set-e-in-a-bash-script-mean

**Comment by tute** [comment]
Oh it's a bash thing. :+1: to this.

**Comment by mcmire** [comment]
Yes, please. :+1:

**Comment by croaky** [comment]
To clarify, the title of this issue is an analogy, not an expected implementation. "It should work like set -e"!is what I was thinking when I wrote it.

**Comment by andyw8** [comment]
I just ran into this due to Nokogiri failing to install. It looks like `bundle install` is run via [bundle_command](http://apidock.com/rails/Rails/Generators/AppBase/bundle_command) which doesn't check the exit code, so it's a little tricky to fix.

**Comment by tute** [comment]
Here is Rails' take on its setup script: https://github.com/rails/rails/pull/20926/files

**Comment by purinkle** [comment]
@croaky, is this something you think would still be useful?

**Comment by croaky** [comment]
Yes, this still seems reasonable to me!

**Comment by thogg4** [comment]
If no one else is working on this I can take a shot at it.

**Comment by thiagoa** [comment]
This issue seems to be stale and out of date. I'm closing it in favor of the following one:

https://github.com/thoughtbot/suspenders/issues/1080

If anyone has more insight into the problem, feel free to comment on the issue above. Thank you ❤️
