### ISSUE TITLE
Could not find "_flashes.html.erb" in any of your source paths.

### ISSUE THREAD

**Issue by rugginoso** [thoughtbot/suspenders#496]
The version of refills (0.2) does not include _flashes.
Specifying ```gem refills, github: 'thoughtbot/refills'``` works, but bundler-audit complains about this solution (also I'm not sure this is the right way as well).

**Comment by delphaber** [comment]
Related to #476 I suppose

**Comment by gabebw** [comment]
Yes, this is the same issue as #476. Please follow that issue for updates & fixes. Thanks!
