### ISSUE TITLE
config.active_record.default_timezone default is already :utc

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#499]
In this commit https://github.com/thoughtbot/suspenders/commit/d8af03a30921d192910b786d7d56745bb2b70639 you set config.active_record.default_timezone to :utc but rails default is already :utc

References:
http://guides.rubyonrails.org/configuring.html

> config.active_record.default_timezone determines whether to use Time.local (if set to :local) or Time.utc (if set to :utc) when pulling dates and times from the database. The default is :utc.

Could it be removed or am I missing something?

**Comment by croaky** [comment]
Maybe our commit came before that was the default? Agreed, it could be removed.
