### ISSUE TITLE
Heroku app naming tries to use underscore

### ISSUE THREAD

**Issue by shawnonthenet** [thoughtbot/suspenders#500]
Running suspenders example.com --heroku

will try to create heroku apps named example_com-production and example_com-staging but heroku only allows letters, numbers and hyphens not underscores so the app creation fails.

**Comment by darokel** [comment]
Aye. Experienced this too.

**Comment by tute** [comment]
We'll need a test and fix for this, making app_name `dasherize`d rather than `underscore`d. PRs welcome! :)

**Comment by tute** [comment]
Closing in favor of PR. Thanks for your input!
