### ISSUE TITLE
No separate Rails staging environment

### ISSUE THREAD

**Issue by croaky** [thoughtbot/suspenders#506]
Use `production` config on Heroku staging:

https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment

**Comment by gabebw** [comment]
I'm confused - what would change in suspenders?

**Comment by gabebw** [comment]
Oh, I see: https://devcenter.heroku.com/articles/deploying-to-a-custom-rails-environment#setting-staging-behavior

I think the idea is to move anything with `if Rails.env.xyz?` to an environment variable instead?

So we still have a staging server and a production server, they just have different values for the same env variables.

**Comment by croaky** [comment]
Yeah, no Rails staging environment, but still a staging server. The staging server would just be running exactly as production, but with different ENV variables and a probably a couple of feature flags.

**Comment by gabebw** [comment]
I do that anyway, actually. I like the idea. I can't find anything we'd have to change in Suspenders, though: https://github.com/thoughtbot/suspenders/search?utf8=%E2%9C%93&q=rails.env

Should this be in the guides instead?

**Comment by croaky** [comment]
@gabebw I think we'd need to do something like this:

https://github.com/thoughtbot/suspenders/compare/dc-staging?expand=1

**Comment by derekprior** [comment]
I'd be curious to see how many additional environment variables this
results in for one of our established apps and if that management (which is
not automated) is deemed worth it.

Is this better as a research card first?

**Comment by croaky** [comment]
Definitely better as a Research card.

**Comment by gabebw** [comment]
I like `dc-staging`. It's exciting! But yes, research card first.

**Comment by jferris** [comment]
I'm not sure we *need* a staging environment. Here's what we use it for:

* Prevent sending emails to random people in staging (could be set with a feature flag, but it could be easy to forget to set/unset that flag for staging/production)
* Report the environment name to services like Airbrake

I'm not really sure what it costs us, though. Agreed that it would be worth trying out on an app before adding it to Suspenders. Should we close this for now?

**Comment by tute** [comment]
I like having [`config/environments/staging.rb`](https://github.com/thoughtbot/suspenders/blob/v1.24.0/templates/staging.rb), and making explicit that it's almost production but we intercept emails. I'm also not sure what excatly we gain, as we can still follow the `ENV` variables for specific configuration.
I'm ok with closing this issue.

**Comment by croaky** [comment]
Created a Research card: https://trello.com/c/rwdcYBdc

Closing the issue for now.

**Comment by tute** [comment]
@jferris implemented this in Upcase (https://github.com/thoughtbot/upcase/pull/1525, requires subscription). Our suspenders' staging env is three lines now. I think it's a good idea to drop it.
