### ISSUE TITLE
Provide a better default ActionMailer `delivery_method` in development env

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/suspenders#516]
It seems that Rails 4.2 defaults to `:deliver` as the default ActionMailer `delivery_method`. Thus, emails will try to deliver via `sendmail`. Seems not very useful in most dev setups. Should we default that to `:test` in development environment instead?

**Comment by jferris** [comment]
I think we should use `:test`, yes.

**Comment by croaky** [comment]
Agreed.

**Comment by tute** [comment]
Closing in favor of PR.
