### ISSUE TITLE
ActiveJob

### ISSUE THREAD

**Issue by ventsislaf** [thoughtbot/suspenders#520]
What are thoughbot's thoughts (how it sounds!) on using `ActiveJob`? Do you think it could bring some value over using `DelayedJob` directly?

I was thinking to open a pull request in which `ActiveJob`'s queue adapter is configured to `:delayed_job` but I want to hear some of your opinions first.

**Comment by derekprior** [comment]
I think we should be using ActiveJob by default, breaking out to queue-specific code only when the ActiveJob API is insufficient.

**Comment by tute** [comment]
@ventsislaf agreed, such a PR would be very welcome!
