### ISSUE TITLE
Gems aren't cached between builds

### ISSUE THREAD

**Issue by teoljungberg** [thoughtbot/suspenders#531]
I noticed that each time I ran my tests on travis it ran `bundle install` on every run.
I got the caching working by copying the .travis.yml file from another project. This is the diff

```patch
diff --git a/.travis.yml b/.travis.yml
index 099bd5a..cd68f6c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,21 +1,17 @@
+language: ruby
+rvm: 2.2.0
+cache: bundler
+sudo: false
 before_install:
-  - "echo '--colour' > ~/.rspec"
-  - "echo 'gem: --no-document' > ~/.gemrc"
-  - export DISPLAY=:99.0
-  - sh -e /etc/init.d/xvfb start
-install:
-  - bin/setup
+  - "export DISPLAY=:99.0"
+  - "sh -e /etc/init.d/xvfb start"
+before_script:
+  - cp .sample.env .env
+  - bundle exec rake db:test:prepare
 branches:
   only:
     - master
-cache:
-  - bundler
-language:
-  - ruby
 notifications:
   email: false
-rvm:
-  - 2.2.0
 addons:
   postgresql: "9.3"
-sudo: false
```

**Comment by derekprior** [comment]
Do we want to cache gems? Seems like we want to re-resolve every time in order to make sure we're testing with latest and greatest everything?

**Comment by tute** [comment]
I'm in favor of caching them. We can bust the cache when we want (hopefully automatically every N hours or days?), or do `bundle update`s locally when we'd like extra assurance.

I think tests take already too long and would be happy with gains that don't significantly reduce our confidence.

**Comment by teoljungberg** [comment]
The cache is automatically busted if you change the Gemfile or the Gemfile.lock

**Comment by tute** [comment]
I just pushed twice the commit implementing this, and saw no obvious improvements: 
![screen shot 2015-03-07 at 11 59 58 am](https://cloud.githubusercontent.com/assets/54260/6542270/99f693d8-c4c1-11e4-8579-3e05b6c700ce.png)

But the `bundle install` step does take around a minute less on builds:
![screen shot 2015-03-07 at 12 01 25 pm](https://cloud.githubusercontent.com/assets/54260/6542276/d2dc4b5c-c4c1-11e4-94e6-62a60c37dbab.png)
![screen shot 2015-03-07 at 12 01 37 pm](https://cloud.githubusercontent.com/assets/54260/6542277/d2ddb62c-c4c1-11e4-837b-bbbff066cd63.png)
![screen shot 2015-03-07 at 12 01 48 pm](https://cloud.githubusercontent.com/assets/54260/6542275/d2dc20fa-c4c1-11e4-9739-a4aec2ac302c.png)
![screen shot 2015-03-07 at 12 02 00 pm](https://cloud.githubusercontent.com/assets/54260/6542278/d2de54ec-c4c1-11e4-8cdb-b2bd166d4c86.png)

I'll merge it if @derekprior is not opposed to it.

**Comment by teoljungberg** [comment]
Thanks @tute
