### ISSUE TITLE
Refills flashes

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/suspenders#537]
There seems to be two sets of `_flashes` partials in `views`: one in `views/application` and the other in `views/refills`.

I believe the `views/refills` partial can be removed (along with the whole `views/refills` directory) and Refills should stop generating that, if it is.

**Comment by tute** [comment]
Can you verify this @tysongach please? I never worked with Rails + Bourbon yet (I'll suspenderize my "breakable toys"), and thus you will have a more educated view of it.
Thank you!

**Comment by tute** [comment]
I see what you mean @tysongach. It seems it's generated somewhere, it shouldn't.

**Comment by tute** [comment]
Closing in favor of PR. Thanks Tyson!
