### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by ventsislaf** [thoughtbot/suspenders#541]
When I install `suspenders` version 1.25.0, in the source code of the gem `.ruby-version` contains `2.2.0` instead of `2.2.1`.

@tute, do you think anything could happened when you released the new version of the gem?

**Comment by tute** [comment]
Related with https://github.com/thoughtbot/suspenders/pull/533.

This is a bug indeed, will investigate. Thanks for noting!

**Comment by tute** [comment]
I packaged an edited version of `.ruby-version`, just released 1.26 with the bugfix. Thanks again!
