### ISSUE TITLE
Configure Capybara Webkit to block unknown URLS

### ISSUE THREAD

**Issue by croaky** [thoughtbot/suspenders#550]
If `--capybara-webkit`, add to `spec/spec_helper.rb`:

```ruby
RSpec.configure do |config|
  config.before(:each, js: true) do
    page.driver.block_unknown_urls
  end
end
```

**Comment by croaky** [comment]
Example issues: http://blog.arkency.com/2015/02/upgrade-capybara-webkit-to-1-dot-4-and-save-your-time/

**Comment by mcmire** [comment]
Is `--capybara-webkit` a default option? Is this going along with the "opt in, not opt out" idea?

**Comment by jferris** [comment]
This makes sense to me to have in the default configuration.

We probably also want to force a bump in the version here: https://github.com/thoughtbot/suspenders/blob/master/templates/Gemfile.erb#L44

**Comment by tute** [comment]
Closing in favor of PR.
