### ISSUE TITLE
Proposal: truncate logs

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/suspenders#558]
On long-running projects, it's not uncommon to see log files grow to several hundred megabytes.

Adding the following for the dev and test environments would help:
```ruby
NUMBER_OF_OLD_LOGFILES_TO_KEEP = 1
MAXIMUM_LOGFILE_SIZE = 5.megabytes
config.logger = Logger.new(config.paths.log.first, NUMBER_OF_OLD_LOGFILES_TO_KEEP, MAXIMUM_LOGFILE_SIZE)
```

**Comment by andyw8** [comment]
Seems there was a PR to Rails for this, but it was rejected: https://github.com/rails/rails/pull/17332

**Comment by mcmire** [comment]
This seems reasonable to me... maybe this should be a development/test only setting?

**Comment by derekprior** [comment]
My concern would be what would happen if this rotation happens in the middle of a request you are debugging by tailing a log?

**Comment by tute** [comment]
I'm in favor of this for development.

**Comment by tute** [comment]
And test.

**Comment by andyw8** [comment]
@derekprior that should be pretty rare occurrence. Assuming a typical request is 1k of log data, it would happen once for every 5000 requests. The log data wouldn't be lost – you would just need to check the rotated log file.

**Comment by tute** [comment]
@andyw8 want to send a PR for this?

**Comment by andyw8** [comment]
Yes, will do.

**Comment by andyw8** [comment]
I haven't got around to this yet but I'll close this in the meantime.

**Comment by tute** [comment]
We can also add something like in https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/bin/setup#L24-L25 to our setup script to start more fresh:

```
ruby bin/rake log:clear tmp:clear
```
