### ISSUE TITLE
Refills Flashes

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/suspenders#562]
I’m seeing some inconsistencies with the Refills Flashes in a new Suspenders project:

1. `application.css.scss` has `@import "refills/flashes";`, but there isn’t actually a `_flashes.scss` Sass partial that exists in the `stylesheets` directory (nor is there a `refills` directory in `stylesheets`).
2. _If_ we do have a `_flashes.scss` partial, it should go in a `components` directory, not `refills`. A `refills` directory inside `stylesheets` is not clear.

**Comment by tute** [comment]
Related with PR: https://github.com/thoughtbot/suspenders/pull/552

**Comment by tute** [comment]
Thanks Tyson! Closing in favor of PRs.
