### ISSUE TITLE
Sass::SyntaxError: File to import not found or unreadable: refills/flashes.

### ISSUE THREAD

**Issue by pbraswell** [thoughtbot/suspenders#568]
I'm trying to deploy to Heroku.  I've done nothing but generate the app and am attempting to deploy.  I get this:

Sass::SyntaxError: File to import not found or unreadable: refills/flashes.

I'm using suspenders v 1.28.0

Thanks,
Peter

**Comment by JoelQ** [comment]
I think this is the same issue as https://github.com/thoughtbot/suspenders/issues/562

I think PR https://github.com/thoughtbot/suspenders/pull/552 is a proposed fix for this

**Comment by pbraswell** [comment]
Yep!  Spot on.

The code in the pull request did the trick:
rails generate refills:import flashes --only-stylesheets

-------------------------------------------------------------
Peter Braswell // peterbraswell.com <http://www.peterbraswell.com>
------------------------------------------------------------

**Comment by tute** [comment]
Yes, known issue, thanks for reporting! I'll close in favor of the PR. (`--only-stylesheets` is desired behavior for now, it doesn't work that way).

**Comment by tute** [comment]
This error is back in current `master`:

```
      create  config/initializers/rack_mini_profiler.rb
Set up stylesheets
Install Bitters
         run  bitters install --path app/assets/stylesheets from "."
Bitters files installed to app/assets/stylesheets/base/base
Install Refills
    generate  refills:import
W, [2016-07-19T21:22:59.497644 #30994]  WARN -- : [SKYLIGHT] [0.10.5] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Could not find generator 'refills:import'. Maybe you meant 'helper', 'generator' or 'rspec:model'
Run `rails generate --help` for more options.
      remove  app/views/refills
Copying miscellaneous support files
 ```
