### ISSUE TITLE
Generate binstubs with spring

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#569]
suspenders includes spring and spring-commands-rspec but binstubs haven't been generated.
I think `bundle exec spring binstub --all` should be executed somewhere (in `suspenders new` or `bin/setup.sh` ?)

What do you think? I can try to submit a pr if this is useful :)

**Comment by tute** [comment]
A PR will be helpful. Thank you!

**Comment by delphaber** [comment]
Ok :) I think it could be executed as one of the last instructions in `suspenders new`

**Comment by tute** [comment]
Closing in favor of PR.
