### ISSUE TITLE
web-console && workers

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#570]
What do you think about this web-console FAQ?

https://github.com/rails/web-console#why-i-constantly-get-unavailable-session-errors

Should `sample.env`include `UNICORN_WORKERS=1`?

**Comment by tute** [comment]
I didn't hear of this problem with suspenders. I assume it does happen to you?

**Comment by delphaber** [comment]
Yep :(

**Comment by delphaber** [comment]
It happens on pristine suspenders app.

![screenshot 2015-06-05 01 17 55](https://cloud.githubusercontent.com/assets/139284/7996487/fcf01fb8-0b20-11e5-92b7-f5f802c424e6.png)

**Comment by bf4** [comment]
web-console is based on (ripped off of?) [better_errors](https://github.com/charliesome/better_errors) which https://github.com/charliesome/better_errors#unicorn-puma-and-other-multi-worker-servers which also recommends one web server...

personally, if I'm ever trying to use this tool, I switch from foreman to rails s so that it 'just works'

**Comment by jessieay** [comment]
I didn't even realize this lib was using `web-console` - good to know. Seeing `UNICORN_WORKERS=1` in `sample.env` seems like a good idea to me.

**Comment by tute** [comment]
I'm :+1: to `UNICORN_WORKERS=1` in `.sample.env`. Pinging @jferris in case he has seen this or thought of other solutions?

**Comment by jferris** [comment]
We stopped using Better Errors on most projects because of issues like this. If this is officially part of Rails now, I guess we'd better get a single-threaded, single-process development server going.

**Comment by tute** [comment]
As of https://github.com/thoughtbot/suspenders/pull/501, we need to configure Puma to use one worker in development.

**Comment by tute** [comment]
> @jferris: We stopped using Better Errors on most projects because of issues like this. If this is officially part of Rails now, I guess we'd better get a single-threaded, single-process development server going.

It's not officially part of rails, we include `web-console` in suspender's Gemfile, if that's what you are referring to.

**Comment by tute** [comment]
Closing in favor of discussion in PR. Thanks!
