### ISSUE TITLE
Several issues with creating new project 

### ISSUE THREAD

**Issue by frankis** [thoughtbot/suspenders#575]
Hi there

This looks pretty promising to me but I am running into issues right from the start.

The gem installs, but triggering "suspenders projectXYZ" I receive several errors:

**First:**
```
Could not find gem 'delayed_job_active_record (>= 0) ruby' in any of the gem sources listed in your Gemfile or installed on this machine.
```
Same goes for flutie, email_validator, high_voltage, i18n-tasks, neat

--> I could fix this manually installing the related gem(s) but after fixing one issue, the next gem was missing.

**Second:**
```
Could not find gem 'email_validator (>= 0) ruby' in any of the gem sources listed in your Gemfile or installed on this machine.
```
--> I could fix this manually installing the related gem

**Third:**
```
...
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
...
```

Also: shouldn´t the final bundle install not better be triggered with "--without production" (and without stage?)

**Comment by tute** [comment]
Thanks for reporting! This is surprising, suspenders should automatically install its dependencies through bundle. What version of Ruby and Bundler are you using? Do you use a Ruby version manager?

**Comment by frankis** [comment]
Hi there
I am on 4.2.1, 2.2.2 for rails, latest bundler & RVM.

I will crosscheck on a clean nitrous workspace.
On Mi., Juni 3, 2015 at 21:21, thoughtbot/suspenders
<reply@reply.github.com>
wrote:
Thanks for reporting! This is surprising, suspenders should automatically
install its dependencies through bundle. What version of Ruby and Bundler are
you using? Do you use a Ruby version manager?

—
Reply to this email directly or view it on GitHub
[https://github.com/thoughtbot/suspenders/issues/575#issuecomment-108586707] .[https://github.com/notifications/beacon/AIRJlazGEYHZUCoGNPix6jz6ICRD6-TTks5oP0tNgaJpZM4EzYLQ.gif]

**Comment by bf4** [comment]
probably a full stack trace would be helpful to debugging... 

also, did you see https://github.com/thoughtbot/suspenders/#dependencies ?

**Comment by frankis** [comment]
Solved: I am 100% unsure why, but deleting the folder, starting from scratch did the job finally.
However, one thing I would like to mention which is worth for being added to the documentation is the fact that keys aren´t created by default and rake secret should be run to create an own key for adding in a related .env file (such as .env.development).

**Comment by tute** [comment]
Surprising. Thanks!
