### ISSUE TITLE
FYI: PG Backups as an add-on has been deprecated

### ISSUE THREAD

**Issue by frankis** [thoughtbot/suspenders#577]
Hi there

As per the heroku dev docs at https://devcenter.heroku.com/articles/pgbackups:

***PG Backups as an add-on has been deprecated.*** The commands exist as part of the Heroku Postgres namespace in the CLI. The new functionality is live and available for use. We also have a mapping guide to show you how the old commands transfer to the new ones.

**Comment by jessieay** [comment]
@frankis I see a reference to pgbackups in the `README`, is it listed somewhere else that I am missing?

**Comment by frankis** [comment]
Seems the docs where updated but its still in the changelog at https://devcenter.heroku.com/changelog-items/623

However, please notice that the text van be pretty misleading but neverthless good to know if you use deprecated commands somewhere.
