### ISSUE TITLE
Refills Flashes

### ISSUE THREAD

**Issue by dikaio** [thoughtbot/suspenders#580]
Suspenders has `@import "refills/flashes";` as a default in application.scss yet the refills flashes stylesheet is not included by default and I was just trying to figure out why it's not included when the new app is being generated? Thanks!

**Comment by dikaio** [comment]
Ok I it's because it's as easy as just using the cli command `rails g refills:import flashes` ?

**Comment by mcmire** [comment]
This is a known issue (see #552), but yes, that's what you have to do for right now.
