### ISSUE TITLE
zsh: command not found: suspenders

### ISSUE THREAD

**Issue by harshamv** [thoughtbot/suspenders#585]
When i try to run the following command i get an error

Sites  suspenders thoughtbot
zsh: command not found: suspenders

I am trying to to find in the readme what path should i add to my ZSH?

**Comment by JoelQ** [comment]
Did you install the gem with `gem install suspenders`? Did you switch ruby versions? Gems are installed per ruby version. Do other CLI tools installed as gems work (e.g. `rails new`) ?

**Comment by harshamv** [comment]
@JoelQ i have installed suspenders. i have the following ruby version ruby - 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14] and am using rbenv for managing ruby. 

yes rails new works.

**Comment by JoelQ** [comment]
Does `gem list suspenders` show anything?

**Comment by harshamv** [comment]
@JoelQ 

gem list suspenders
*** LOCAL GEMS ***
suspenders (1.29.0)

**Comment by JoelQ** [comment]
You may need to `rbenv rehash` https://github.com/sstephenson/rbenv#rbenv-rehash

**Comment by harshamv** [comment]
@JoelQ weird when i try now its all working fine :(

if i have a previously used app which used suspenders and want to change the ruby version to the latest. Mine is ruby - 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

How can i do it? when i try to run bundle it says rbenv doesnt have 2.2.0 ruby version.

**Comment by JoelQ** [comment]
You will probably want to edit the `.ruby-version` file and the ruby version declaration at the top of the `Gemfile` to be 2.2.2

**Comment by harshamv** [comment]
thank you @JoelQ
