### ISSUE TITLE
Creating heroku and deployment layer after the app was created

### ISSUE THREAD

**Issue by liptonshmidt** [thoughtbot/suspenders#589]
First of all, thanks for your work! Suspenders are cool :)

I've played with it and found myself in situation where the app was initially created without the --heroku option and the decision to deploy was made a little bit later.

Of course, it is not big deal to set up all the deployment stuff manually; but I thought that it will be great if it is possible to just use suspenders generator to create deployment layer anytime later after the app was built (including such goodies as your ./bin/deploy script).

I understand that it may increase overall complexity of the lib and may condradict with the philosophy of keeping suspenders as simple as possible; However, I'll be glad to hear your opinion about this possible enhancement.

**Comment by mcmire** [comment]
We have definitely kicked around the idea of including some kind of standalone generators with Suspenders -- see https://github.com/thoughtbot/suspenders/pull/511#issuecomment-72874292 -- so I feel like this could be accomplished using such a mechanism. That said, no work has been done on that yet.

**Comment by liptonshmidt** [comment]
Thank you for the quick reply, I'll read through the discussion.

**Comment by tute** [comment]
I'd like to see this. A PR like #511 would definitely help. Closing for now as I don't expect to work on this in the foreseeable future, but happy to test drive and polish PRs together!
