### ISSUE TITLE
Always deploy master branch

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/suspenders#591]
Right now our `deploy` script will deploy from the current branch the user is on. This isn't straight forward, and a bit confusing. We ran into this on a current project.

Thoughts on always deploying the master branch? Perhaps there can be added an option like `--branch, -b` if we want to provide non-master branch deployment as a feature.

**Comment by mcmire** [comment]
I would probably find such behavior even more confusing.

What if we instead gave an error message to tell people to switch to the master branch before deploying?

**Comment by christoomey** [comment]
I regularly use the fact that the deploy script pushes the current branch to deploy non-master branches to staging to test in a production-like environment.

I've personally never had an issue / confusion around this, but if enough others have this issue I'd suggest requiring an option (but using the current branch, not specifying) to deploy a non-master branch:

``` sh
# Deploying from master remains the same
$ git branch
  feature-branch
* master

$ bin/deploy production
# succesful
```

``` sh
# deploying a non-master branch requires --branch (or -b) switch
$ git branch
* feature-branch
  master

$ bin/deploy production
# fail with warning "Non on master branch. Use '--branch' to deploy"

$ bin/deploy --branch production
# succeeds, using current branch
```

**Comment by paulcsmith** [comment]
I like the explicit `--branch` idea. We've been bitten a few times where a developer that's not used to the script accidentally deployed the wrong branch to staging. It has happened a few times. The `--branch` would definitely help.

**Comment by bernerdschaefer** [comment]
Whatever is decided here, it would be good to reflect it in parity as well. Its `deploy` sub-command always deploys from master, and does not (yet?) support a flag to deploy a non-master branch.

**Comment by tute** [comment]
> I regularly use the fact that the deploy script pushes the current branch to deploy non-master branches to staging to test in a production-like environment.

I feel the same.

If it makes it more clear, I'm ok with a nice error message and requiring a `--branch` option for deploying non-master branches.

**Comment by tute** [comment]
@gylaz any further thoughts on this?

**Comment by gylaz** [comment]
The warning and an option sounds like a good solution.

I originally opened this PR, because a client developer found it confusing. I personally am okay with the current behavior, as a long as it's clear what to expect. Providing an option might be a good guard, but I'm not completely sure we need it. I'd be also okay with closing this and agree with @bernerdschaefer that `parity` should probably behave the same.

**Comment by tute** [comment]
Hi @geoffharcourt! Are you maintaining parity these days? What do you think of the branch mismatch between parity and suspender deploy scripts?

**Comment by geoffharcourt** [comment]
Hi @tute, I have https://github.com/thoughtbot/parity/pull/50 to always deploy non-production branches to staging/master. For the same reason that @christoomey described above, I want to be able to test a feature branch on staging without having to merge to master, which I only want to do when I believe I have a candidate for deploy (after CI finishes, of course).

**Comment by tute** [comment]
Great, in that cases both projects are about to be in sync, and we can leave current behavior in suspenders. Or do your same override: only deploy master to production, and allow any branch in other environments. Thank you!

**Comment by tute** [comment]
@gylaz, do you think we should rename this to "Always deploy master branch *for production*", and work on a PR, or close it because we seem to be fine with current behavior?

**Comment by gylaz** [comment]
I'm cool with closing this.

**Comment by tute** [comment]
Thank you!

**Comment by geoffharcourt** [comment]
Thanks everyone, glad to have these two projects more in sync.

**Comment by gylaz** [comment]
I wonder if suspenders should just install parity, then we can remove `bin/deploy` and not have to sync the two projects?

**Comment by jferris** [comment]
@gylaz I think we want to have `bin/deploy` either way, because not every project will have the same deploy steps as parity. Projects can use other languages or have extra steps like expiring a cache.

**Comment by geoffharcourt** [comment]
Parity is moving to encourage installation by apt or Homebrew, I'm not sure
if we have decided to discourage gem installations.
