### ISSUE TITLE
Setting page title in static pages

### ISSUE THREAD

**Issue by LimeBlast** [thoughtbot/suspenders#600]
I was wondering if anyone had a work around for setting page titles in high_voltage static pages?

I'm new to Suspenders. It looks like at one point in time you could use Flutie for `page_title`, allowing you to specify the page title in the view file.

This appears to have since been removed in favour of using Title, and as such, I can't figure out what I need to do to set the page titles for my static pages.

Cheers.

**Comment by mcmire** [comment]
Flutie is still a gem in the Gemfile, so you can still use that instead of Title, if you like. You'll want to replace the content of the `<title>` tag in the application layout to use the `page_title` helper, and then you can use `content_for :page_title` in the views for the static pages.

**Comment by derekprior** [comment]
Assuming you had `pages/about` I think you'd follow a similar `controller.action` naming scheme for the key. So: `pages.about: About Us`.

**Comment by LimeBlast** [comment]
@mcmire thank you.

@derekprior I tried that, didn't work. I also tried `titles.high_voltage-pages.about` and `titles.high_voltage-pages.show` (which is being reported as the controller and the action by the body tag class), which also didn't work.

**Comment by tute** [comment]
The right structure for showing those titles is:

﻿```yaml
en:
  titles:
    application: Temp
    high_voltage:
      pages:
        show: "Title for all pages"
```

Now this means that we can't use a different title for each HighVoltage page with the `title` gem. I'd like to be able to define the `id` too so these gems interact with each other in a friendlier way. @calebthompson do you think this counts as an issue for `title`?

**Comment by tute** [comment]
Closing, as this is not an issue for suspenders but the interaction of those two gems.

**Comment by tute** [comment]
`@title_options = { page_title: params[:id].capitalize }`, with `pages.show: "%{page_title}"` makes this work.

**Comment by calebthompson** [comment]
Are you sure? I'd be surprised. It would work, I think, if it were just `@title_options = params[:id].capitalize` and `pages.show: "%{title_options}"`.

Then again, I could be wrong.

Something like this could work:

```
@high_voltage_title = t(params[:id], scope: "high_voltage.pages.show")
high_voltage.pages.show: "%{high_voltage_title}"
```

**Comment by mcmire** [comment]
I think that the `page_title` from flutie does a much better job at this.

I've had success with this pattern in the past:

``` erb
<%- in the view %>
<% content_for :page_title, t("titles.your_custom_title") %>
```

``` yaml
# in en.yml
titles:
  your_custom_title: Your Custom Title
```

**Comment by calebthompson** [comment]
For a general solution I think the translation backed solution I mentioned using t(params[:id], scope: pages.show) is better.
