### ISSUE TITLE
Add Heroku Pipelines support

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/suspenders#617]
Hey guys,

I'd be very interested to hear if you use the Beta release of Heroku Pipelines yet...

https://devcenter.heroku.com/articles/pipelines

Best,

Rikki

**Comment by tute** [comment]
We happily do.

**Comment by rikkipitt** [comment]
Hi @tute, sorry for the delay. What I was eluding to was whether or not this will supersede how suspenders currently handles staging and production apps? I'd be very interested to hear how you guys make use of this new lab feature in the coming months. Do you have any plans to write up a blog article about the subject?

Cheers!

**Comment by tute** [comment]
> Hi @tute, sorry for the delay. What I was eluding to was whether or not this will supersede how suspenders currently handles staging and production apps? I'd be very interested to hear how you guys make use of this new lab feature in the coming months. Do you have any plans to write up a blog article about the subject?

Thanks for your questions, @rikkipitt! I haven't personally used it yet, so I'm not sure what code changes would be appropriate for suspenders yet, or if at all.

Delegating the questions to @bernerdschaefer and @calebthompson, who have had good experiences with this. Thank you all!

**Comment by rikkipitt** [comment]
Thanks guys, I've had chance to sit down and have a play with this today. It looks like you probably won't need to change how it creates separate apps for each environment as that is a requirement of pipelines. We could, however, automate the creation of the pipeline (add each of the apps) and possibly add "promote" functionality to `./bin/deploy` when this all becomes stable...

**Comment by rikkipitt** [comment]
I've found that when promoting an app from staging to production, some asset paths aren't updated and have the full path of the staging version... Have you guys experienced this yet? I assume it's because of the use of the ```asset_host``` config.

```config.action_controller.asset_host = ENV.fetch("ASSET_HOST", ENV.fetch("HOST"))```

**Comment by tute** [comment]
We'll need a template for `app.json`, and add `heroku pipeline` commands during setup.

**Comment by tute** [comment]
See also: https://gist.github.com/elle/966fbf9d37924f991209

**Comment by rikkipitt** [comment]
Useful, thanks @tute. Do you think it's worth re-compiling assets in a postdeploy/promotion command to mitigate the above assets issue? Unless I simply have incorrect ```ASSET_HOST``` settings... what do you folks use for staging and production?

**Comment by reshleman** [comment]
@rikkipitt I was looking into this, too, and found this warning in [Heroku's help article on Pipelines][1] helpful:

> When promoting slugs between apps, Heroku will copy the slug verbatim between apps, without changes. In particular, the slug is not rebuilt with the environment of the target app. If your builds tend to bake in environment from the build-app context, then your slugs will not be portable between apps, and will not work correctly when promoted from the app where they were built. This may be the case, for example, if you’re using Ruby on Rails and the asset pipeline to build assets hosted at a CDN defined by a URL in your build environment. This is because URLs specific to the build-app will be baked into css and js-files, and those will not work or not work correctly when promoted.

When Heroku starts a dyno, it loads the application from the [slug][2]; with pre-compiled assets, the slug will contain references to your environment's `ASSET_HOST` value, as you observed.

Heroku automatically runs `rake assets:precompile` [in the process of building the slug][3] when you push a new commit. As far as I know, re-running that task *after* the slug has been compiled (i.e., if you were to change the value of `ASSET_HOST`, but without pushing a new commit) won't actually make any changes to the already-compiled slug.

This leads me to believe that Pipelines won't play well with the `asset_host` configuration, but I'd be happy to be proven wrong.

[1]: https://devcenter.heroku.com/articles/pipelines
[2]: https://devcenter.heroku.com/articles/slug-compiler
[3]: https://devcenter.heroku.com/articles/rails-asset-pipeline#compiling-assets-during-slug-compilation

**Comment by rikkipitt** [comment]
Thanks @reshleman. It's starting to sound like we might not be able to make use of the Pipeline benefits... I'll conduct some tests tomorrow to see if the slug is immutable or not.

**Comment by rikkipitt** [comment]
@tute those crowdwise links in https://github.com/thoughtbot/suspenders/issues/617#issuecomment-148787534 seem to be broken, are they internal to you folks?

**Comment by tute** [comment]
> @tute those links in #617 (comment) seem to be broken, are they internal to you folks?

yes, I removed them

**Comment by rikkipitt** [comment]
Sadly, I've just heard from Heroku support that there are no triggers for Rake tasks after promotion.

> One idea would be to use the same ```ASSET_HOST``` across apps. If your CDN is using proper expiration, and your app is using the asset pipeline, unique files will be created such that they can all exist on the same CDN without running into each other.
> Jon @ Heroku Support

Is Amazon Cloudfront an option here?

**Comment by rikkipitt** [comment]
Just got this back from Jon at Heroku:

> Hey Rikki --
> It's actually being worked on as we speak. We should have something in Beta in the next few weeks.
> -Jon

**Comment by tute** [comment]
> I've found that when promoting an app from staging to production, some asset paths aren't updated and have the full path of the staging version... Have you guys experienced this yet? I assume it's because of the use of the asset_host config.
> 
> config.action_controller.asset_host = ENV.fetch("ASSET_HOST", ENV.fetch("HOST"))

@iwz did you deal with this issue in your setup? If so, how do you work it out?

**Comment by tute** [comment]
Another issue with suspenders is rack-canonical, which redirects the app to staging with current configuration.

**Comment by tute** [comment]
> Useful, thanks @tute. Do you think it's worth re-compiling assets in a postdeploy/promotion command to mitigate the above assets issue? Unless I simply have incorrect ASSET_HOST settings... what do you folks use for staging and production?

Something like this in staging makes it work:

```ruby
config.action_controller.asset_host = "#{ENV.fetch("HEROKU_APP_NAME")}.herokuapp.com"
```

**Comment by tute** [comment]
Useful commands while setting up an app today (notes to myself):

```bash
# Set up heroku pipelines plugin
heroku plugins:install heroku-pipelines

# Create a pipeline, add applications
heroku pipelines:create -a app-name-staging
heroku pipelines:add -a app-name-staging app-name
heroku pipelines:add -a app-name-production app-name

# Set up (by hand for now) an initial database from staging, plus branch migrations
heroku pg:pull DATABASE_URL app_name_development --app app-name-staging
rake db:migrate
heroku pg:reset DATABASE_URL --app app-name-staging-pr-### --confirm app-name-staging-pr-###
heroku pg:push app_development DATABASE_URL --app app-name-staging-pr-132
```

Will work on this on Friday.

**Comment by iwz** [comment]
> > I've found that when promoting an app from staging to production, some asset paths aren't updated and have the full path of the staging version... Have you guys experienced this yet? I assume it's because of the use of the asset_host config.

> > config.action_controller.asset_host = ENV.fetch("ASSET_HOST", ENV.fetch("HOST"))

> @iwz did you deal with this issue in your setup? If so, how do you work it out?

@tute no, i haven't gotten that far along yet in my greenfield app.

**Comment by tute** [comment]
Another note: we might need to remove auto deploy from Circle CI after this.

**Comment by calebthompson** [comment]
Pipelines and github deploy are technically separate features. I like both.

**Comment by tute** [comment]
Closing in favor of PR: https://github.com/thoughtbot/suspenders/pull/639. Thank you! :clap:

**Comment by tute** [comment]
I said "closing in favor of PR: #639" but didn't close. Here it goes!

**Comment by rikkipitt** [comment]
Cheers @tute, I'll keep an eye on #639

Rikki

**Comment by eliotsykes** [comment]
Apologies in advance for appending/hijacking this closed discussion, however you're the only other folk I've found discussing this issue so I hoped we could help each other out regarding Heroku pipelines using the same assets and so `asset_host` for staging and production.

@rikkipitt Did you happen to hear back from Jon at Heroku on running post-promotion rake tasks?

I believe I'm encountering a similar issue to what you were discussing, in that the compiled `application.css` contains hardcoded CDN URLs. As a result, the staging CDN URL is in the `application.css` asset served by the production environment.

The fix I'm considering:
1. Set `asset_host` to a replaceable token, e.g. `@CDN_HOST@` for the CSS files only:

```ruby
config.action_controller.asset_host = Proc.new do |source, _request|
  if source.end_with?('.css')
    '@CDN_HOST@'
  else
    ENV['ASSET_HOST']
  end
end
```

2. Then add a rack middleware before the `Static` middleware to replace `@CDN_HOST@` in any `*.css` files with `ENV['ASSET_HOST']`.

```ruby
response_body.gsub!('@CDN_HOST@', ENV['ASSET_HOST'])
```

There will be a small cost the first time a new version of a `*.css` file is requested, however after that it will be cached by the current environment's CDN so the above `gsub!` won't happen often.

Can you see any issues with this or do you happen to have an alternative solution?
