### ISSUE TITLE
PG::ConnectionBad when creating a new suspenders app

### ISSUE THREAD

**Issue by Ghi102** [thoughtbot/suspenders#621]
Here's what I did in a terminal (running in Manjaro Linux):

suspenders testapp
rails server

When I go to localhost:3000, I get a PG::ConnectionBad error, with the following text:

could not connect to server: Connection refused Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432? could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432?

I also get the following in the terminal when running "suspenders testapp":

Setting up database
       force  config/database.yml
         run  bundle exec rake db:create db:migrate
could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Followed by a myriad of error messages. bundle install completed, so I'm not missing any gems. Postgresql 9.4.4-2 is installed.

**Comment by mcmire** [comment]
You say Postgres is installed, but is it running?

**Comment by tute** [comment]
@Ghi102 do you need help checking if postgresql is running? Are you in Mac, Linux or Windows?

**Comment by Ghi102** [comment]
@mcmire Yes, that must be it, I didn't know it had to be running to work with suspenders.

@tute I actually wouldn't mind a bit of help to check if it's running/make it running. I'm on Manjaro Linux.

**Comment by tute** [comment]
Manjaro Linux is based off of Arch. Can you follow these instructions? https://wiki.archlinux.org/index.php/PostgreSQL

I'll close this issue as it's not an issue with suspenders, but I'm happy to continue this thread until we solve your current configuration thing. Thanks!

**Comment by Ghi102** [comment]
Thanks for the help I got it to work, I followed what was written in these instructions but had to create a new user with my Linux username (inside postgres). It works now, thanks a lot!
