### ISSUE TITLE
Generate an empty spec/factories.rb file

### ISSUE THREAD

**Issue by thorncp** [thoughtbot/suspenders#622]
Our guides say

> Use one factories.rb file per project.

and the factory_girl_rails documentation says

> If you use factory_girl for fixture replacement and already have a factories.rb file in the directory that contains your tests, factory_girl_rails will insert new factory definitions at the top of factories.rb.

If suspenders generates that file, it'll be easier to conform to our guide.

**Comment by tute** [comment]
:+1:

**Comment by salbertson** [comment]
@thorncp just ran into this today. I think we should create an empty file with an empty `define` block.

**Comment by tute** [comment]
Thanks! Closing in favor of PR.
