### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/suspenders#629]
Hi i have notice this in some gems i think maybe is for El Capitan permissions. Is there any solution of this?
![captura de pantalla 2015-10-17 a las 5 06 27 p m](https://cloud.githubusercontent.com/assets/11930063/10561516/864b8f7e-74f1-11e5-8c53-f06b58a2b0fe.png)

Thanks.
Using Mac OSX 10.11

**Comment by tute** [comment]
Do you use homebrew Ruby or system Ruby? Can you tell me the output of:

- `which -a ruby`
- `which -a gem`
- `ruby --version`

What happens if you try to install it without `sudo`?

Thanks for reporting.

**Comment by Xosmond** [comment]
I did it and the result is this:
![captura de pantalla 2015-10-18 a las 11 10 38 a m](https://cloud.githubusercontent.com/assets/11930063/10564892/2f83d582-7589-11e5-8112-b6f181ef1162.png)

I have been thinking about update ruby to 2.2.3.

**Comment by tute** [comment]
> I have been thinking about update ruby to 2.2.3.

Suspenders requires this. Can you set up homebrew, and newest Ruby following https://gorails.com/setup/osx/10.11-el-capitan, and see if this ends up working?

Thanks!

**Comment by Xosmond** [comment]
That was the problem but im experimenting more, its like 10.11 has removed many things and configurations that i had. Well im resolving now problems with nokogiri. Thanks.

**Comment by tute** [comment]
:+1:
