### ISSUE TITLE
Should `rails_helper.rb` include `spec_helper`?

### ISSUE THREAD

**Issue by salbertson** [thoughtbot/suspenders#631]
We recently used `suspenders` on a new app and had to require `spec_helper` in `rails_helper.rb`. Should this be the default behavior?

**Comment by jferris** [comment]
On a new Suspenders app, you should have this `.rspec` file:

    --color
    --require spec_helper

That will automatically include `spec/spec_helper.rb` everywhere. Is that file missing in your app?

**Comment by calebthompson** [comment]
It is.

**Comment by tute** [comment]
Thanks!
