### ISSUE TITLE
Simple Form error when running Rake on directory

### ISSUE THREAD

**Issue by Fourfingerz** [thoughtbot/suspenders#640]
When I ran `rake` on the suspenders directory, I saw this error message produced 11 times:

> [Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.

This really needs some good ol' clean up.

**Comment by tute** [comment]
Similar issue: https://github.com/thoughtbot/suspenders/issues/452.

This shouldn't happen indeed.

**Comment by Fourfingerz** [comment]
A little update: Running `rake` on a fresh suspenders generated Rails directory doesn't throw the aforementioned simple form error. It is only when I run `rake` on the cloned repo that throws that error.

**Comment by tute** [comment]
@Fourfingerz please don't forget to ask in SimpleForm the question we prepared. Mention me so we work on it together!

**Comment by Fourfingerz** [comment]
Oh, I didn’t forget at all! I was working on my client’s project all weekend and writing tests. 
I’m going to some hacker hours tonight and I’ll post over at SimpleForm and start investigating that problem!

Looking forward to working with you on Tuesday!

-JC

**Comment by Fourfingerz** [comment]
Submitted this issue over to the Simple Forms board! Let's see what they say.

**Comment by tute** [comment]
Link: https://github.com/plataformatec/simple_form/issues/1316

**Comment by tute** [comment]
One unnecessary warning is being worked on https://github.com/plataformatec/simple_form/issues/1316.
