### ISSUE TITLE
Parser Syntax Error

### ISSUE THREAD

**Issue by antwonlee** [thoughtbot/suspenders#644]
I am new to using suspenders. :grin:
Getting these errors when I am running tests, is this something that I am doing wrong in my end?

```
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
```

**Comment by antwonlee** [comment]
I needed to install ruby version 2.2.3

**Comment by mcmire** [comment]
That's a very interesting error. Is there a backtrace you could post?

**Comment by zamith** [comment]
This is a very common error, you can read a bit more about [here](https://github.com/whitequark/parser/issues/189).
