### ISSUE TITLE
bundler audit scan reports successful with update failure of vulnerability db

### ISSUE THREAD

**Issue by eliotsykes** [thoughtbot/suspenders#650]
`bin/rake bundler:audit` updates the vulnerability db then runs the audit scan. 

The update stage can fail (say due to restrictive firewall), but this will not stop the audit scan from reporting that it completed successfully.

One potential issue with this is that the audit will be reported as successful with an out-of-date vulnerability db.

More info at https://github.com/rubysec/bundler-audit/issues/114

Would a temporary fix would be welcome in suspenders to catch this issue until/if the issue is fixed in bundler-audit?

**Comment by mcmire** [comment]
Definitely! Go right ahead.

**Comment by tute** [comment]
> Would a temporary fix would be welcome in suspenders to catch this issue until/if the issue is fixed in bundler-audit?

I'd welcome it if it were simple. I personally am used to seeing bundler audit's successful output, and I see it many times a day. If I see it fail once I'll notice, and if it persists I will worry enough to take a look at what and why is happening.

Solving the issue for real (merging a newer version dependency when it's available with the expected exit code) is a certain :+1: from me.

**Comment by tute** [comment]
Thanks for your input!

**Comment by tute** [comment]
Closing in favor of PR, which will be simpler thanks to bundler-audit's merge of the fix! Thank you for your input.
