### ISSUE TITLE
Prepare release v1.34.0

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#656]
Following steps described in https://github.com/thoughtbot/suspenders/blob/master/RELEASING.md, we need to prepare a new release for this gem. Please send a new Pull Request with an updated `NEWS.md` file (see changes in commits in https://github.com/thoughtbot/suspenders/compare/v1.33.0...master), and an updated `version.rb` file.

We'll merge it, and release a new version of the gem!

**Comment by zamith** [comment]
What is the reason for the new version? Do we release periodically, or are there enough or important new features to warrant a new version?

**Comment by tute** [comment]
I release every ~3 weeks if there are at least >5 commits. Also, I created this issue for use in http://www.meetup.com/hackerhours/events/226693704/ :wink:
