### ISSUE TITLE
Suspenders should be automated using CircleCI

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#662]
Since the generator uses CircleCI, wouldn't it make sense for the gem to be tested using CircleCI?

Would it also make sense to auto-package and release the gem if all tests pass? That would change your current release scheme, but maybe PATCH releases automatically? (MAJOR.MINOR.PATCH)

Just curious as to your thoughts before I submitted a PR.

**Comment by tute** [comment]
> Since the generator uses CircleCI, wouldn't it make sense for the gem to be tested using CircleCI?

I don't mind this. The gem itself has a different set of dependencies (`Gemfile`) than the generated project. In particular, it uses a different CI, and both behave pretty similarly, both work well, and we rarely make changes to the Travis configuration (it works well).

> Would it also make sense to auto-package and release the gem if all tests pass? That would change your current release scheme, but maybe PATCH releases automatically? (MAJOR.MINOR.PATCH)

Interesting, I never thought of releasing per commit. I don't feel strongly that we should (or should not) release that often. We've been lately releasing every ~3 weeks, typically including ~5 changes to the repo.

@jferris @mike-burns, what do you think of this idea?

**Comment by mike-burns** [comment]
I prefer manually releases; they're more cohesive. But I don't feel strongly about this.

**Comment by jferris** [comment]
I feel the same way as @mike-burns.

**Comment by tute** [comment]
I also feel more comfortable releasing every few features/weeks. Ok with closing this issue, @toobulkeh?

**Comment by toobulkeh** [comment]
Fine by me. I was just curious. I'm moving our fork to CircleCI
