### ISSUE TITLE
Forego uses different port than APPLICATION_HOST

### ISSUE THREAD

**Issue by grantovich** [thoughtbot/suspenders#665]
6b7614a8dc7ff2a7dd32d087039e49fd5984a35d switched from Foreman to Forego, and removed the `.foreman` file that told Foreman to use port 3000. Forego uses port 5000 by default, but the Suspenders sample `.env` file still has `ASSET_HOST` and `APPLICATION_HOST` set to `localhost:3000`.

According to a42ec7e773ad79ee8a6d994012c9bd94810c43c2 using port 5000 is undesirable, so probably the solution would be to have Forego use port 3000 as Foreman previously did. It seems there is no Forego equivalent to the `.foreman` file, though there is an open PR at https://github.com/ddollar/forego/pull/56. For me, adding `PORT=3000` to the `.env` file worked, but I have a vague feeling this might conflict with other tools.

Any thoughts on the correct way to resolve this? I'd be willing to put together a PR.

**Comment by tute** [comment]
Thanks! Closing in favor of PR.
