### ISSUE TITLE
Switch from Airbrake to Honeybadger

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#667]
Consensus at thoughtbot seems to be that Honeybadger provides a better experience than Airbrake.

This should be encoded into suspenders, by making it default to Honeybadger instead of Airbrake.

**Comment by mcmire** [comment]
Was there a research card on this? I couldn't seem to find one.

**Comment by tute** [comment]
@calebthompson once pointed me to it. Caleb, do you know how to find it?

**Comment by tute** [comment]
Closing in favor of PR.
