### ISSUE TITLE
Stylize 404 and 500 error pages

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#673]
Rails should show by default 404 and 500 pages with the application's layout, instead of the normal Rails-default bare html pages.

Sample (a bit pseudo) code from `app/controllers/application_controller.rb` from a project I have worked on in the past:

``` ruby
  if Rails.env.production?
    rescue_from ActionController::RoutingError, with: :route_not_found
    rescue_from ActiveRecord::RecordNotFound, with: :route_not_found
    # Are there others?

    rescue_from NoMethodError, with: :internal_server_error
  end

  def internal_server_error
    notify_exception
    render "errors/500.html", status: :internal_server_error
  end

  def route_not_found
    notify_exception
    render "errors/404.html", status: :not_found
  end
```

**Comment by mcmire** [comment]
That's essentially what I've done in the past, I believe.

Instead of using `Rails.env.production?`, what do you think about using the Rails configuration option that controls whether exception detail pages are shown (they're usually shown in development)? I think what you might want to say is, if exception detail pages are NOT being shown, then render a 404 or 500 page. A consequence of this is that 404/500 pages would then be rendered in test mode -- but I think that might be what you want, to simulate what would happen in production mode.

**Comment by toobulkeh** [comment]
Where does thoughtbot sit on authorization? I know it's pretty deep (requires an authentication method as well) but including 401/403 errors here might be a good idea, since they're HTTP standard instead of implementation method dependent.

**Comment by tute** [comment]
If it's HTML format, we redirect with flash messages; and if it's JSON we don't need the view.

We make use of the different HTTP status messages as described by the spec, but I don't think we need to handle more than 404 and 500 in this case (for suspenders).

**Comment by toobulkeh** [comment]
That makes sense -- so you're saying that redirect `:back` or to `root_url` is a good default with any Authorization section?

For example, [CanCanCan](https://github.com/CanCanCommunity/cancancan#3-handle-unauthorized-access) and [Pundit](https://github.com/elabs/pundit#rescuing-a-denied-authorization-in-rails) both have handlers for the default exception handling.

Do you have a default response for 401 / 403 at large? I totally agree that receiving a 401/403 page is a bad UX, but while developing MVPs we are currently operating on the mindset that early adopters can receive detailed errors so they're more understanding of the system at large. Not to mention it's easier to develop against a 401/403 (refresh vs. back & resubmit).

Are you saying that Authorization is outside the scope of Suspenders?
Sorry for hijacking this post if that's the case -- I saw a relation to another problem in the original request.

**Comment by tute** [comment]
> Do you have a default response for 401 / 403 at large? I totally agree that receiving a 401/403 page is a bad UX, but while developing MVPs we are currently operating on the mindset that early adopters can receive detailed errors so they're more understanding of the system at large. Not to mention it's easier to develop against a 401/403 (refresh vs. back & resubmit).

Again, I think of 401 and 403 responses only in JSON format, and in that case, you can define the JSON response format and messaging. HTTP status code is probably enough information, when used well.

> That makes sense -- so you're saying that redirect :back or to root_url is a good default with any Authorization section?

For HTML format, that would do it I believe.

> Are you saying that Authorization is outside the scope of Suspenders?

Yes, it is. Some projects use only `before_action`s, others pundit, and so on.

**Comment by mike-burns** [comment]
@tute I'm trying to close out any issues that are feature requests.

Do you still plan to work on this? Do you mind if I close it, and we can further discuss in a PR?

(Also, hi! How are you! I hope you visit someday!)

**Comment by tute** [comment]
Good to close, I remember there were alternative ways to implement this,
which makes the perfect case for building as a generator. Thanks for your
work!

Also hi! I’m good, and I look forward to seeing you all again! 😃👋🏼
