### ISSUE TITLE
LoadError when generating new project.

### ISSUE THREAD

**Issue by jdbann** [thoughtbot/suspenders#674]
I'm getting an issue loading 'rails/generators' when trying to generate a new suspenders project. I wouldn't be surprised if this is an issue with the way I have set things up, but I'm on a fresh install using the thoughtbot laptop script and dot files.

I'm using rbenv and running `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]` and `Rails 4.2.5`

```
~ % suspenders mes
/Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- rails/generators (LoadError)
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/suspenders-1.34.0/lib/suspenders/generators/app_generator.rb:1:in `<top (required)>'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/suspenders-1.34.0/lib/suspenders.rb:2:in `<top (required)>'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/jdbann/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/suspenders-1.34.0/bin/suspenders:7:in `<top (required)>'
	from /Users/jdbann/.rbenv/versions/2.2.3/bin/suspenders:23:in `load'
	from /Users/jdbann/.rbenv/versions/2.2.3/bin/suspenders:23:in `<main>'
```

**Comment by jdbann** [comment]
I had two versions of Rails installed, 4.2.3 and 4.2.5. Uninstalling 4.2.3 has sorted this.

**Comment by tute** [comment]
That's surprising, I've never seen this. If it's reported again or we known of a way to fix it, let's do it. Thanks for your report!

**Comment by tute** [comment]
I have `rails (4.2.5, 4.2.4, 4.2.3, 4.2.1, 4.2.0, 4.1.12, 3.2.22)` installed, and can't replicate this issue. @jdbann or @seanpdoyle, how can I replicate it, if you know?

**Comment by jdbann** [comment]
Just reinstalled `rails 4.2.3` alongside `rails 4.2.5` and it gave the same error

**Comment by thiagogabriel** [comment]
I have ruby 2.2.3p173, rails (4.2.5, 4.2.4, 4.2.2) and rbenv 0.4.0 and I'm with the same problem.
Uninstalling all rails and installing only 4.2.5 solved for me.

**Comment by jdbann** [comment]
I can also confirm that on the same ruby version `ruby 2.2.3p173` I would get this error with any combination of multiple rails gem versions but it would work fine with only a single version.

**Comment by delphaber** [comment]
+1

**Comment by tute** [comment]
I won't be able to work on this for a few weeks, I'll happily merge a PR if you send one! Thanks for reporting.

cc @rjewell2200

**Comment by jdbann** [comment]
@tute Which ruby version were you using when you tried this?

**Comment by tute** [comment]
I haven't tried to trigger this with more rails versions yet. I use `2.2.3p173`.

**Comment by iovis9** [comment]
Same problem, same ruby version ruby 2.2.3p173
rails (4.2.5, 4.2.4, 4.2.3, 4.2.1)

**Comment by thiagogabriel** [comment]
@tute Changing Suspenders::RAILS_VERSION to "4.2.5" instead of "~> 4.2.0" did the trick. Does it make sense to send a PR changing it or do you prefer to investigate more?

**Comment by tute** [comment]
> Changing Suspenders::RAILS_VERSION to "4.2.5" instead of "~> 4.2.0" did the trick. Does it make sense to send a PR changing it or do you prefer to investigate more?

I'd rather find another solution. Fixing the patch version requires more maintenance than leaving it undefined. Thanks for your input, Thiago!

**Comment by tute** [comment]
> @tute Changing Suspenders::RAILS_VERSION to "4.2.5" instead of "~> 4.2.0" did the trick. Does it make sense to send a PR changing it or do you prefer to investigate more?

In my previous message I said I didn't prefer this, but I think I was mistaken. @thiagogabriel, moving it to `~> 4.2.5` fixes this problem? If so, please do send a PR, and I'll merrily merge it! Thank you.

**Comment by thiagogabriel** [comment]
@tute suspenders is requiring Ruby >= 2.3.0. Even reinstalling other Rails versions listed above I can't replicate the problem. Looks like it is solved.
Can you guys try again? @iovis9 @jdbann @delphaber 
I have `rails (4.2.5.2, 4.2.4, 4.2.2, 4.2.1)` installed on Ruby 2.3.0

**Comment by tute** [comment]
Closing for now, if it continues to be a problem let me know and we'll reopen and work through it. Thank you!
