### ISSUE TITLE
warning: constant ::TimeoutError is deprecated

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#686]
https://github.com/thoughtbot/suspenders/blob/master/templates/errors.rb#L26 uses `TimeoutError` but now (ruby 2.3.0) that constant is deprecated.

Should I remove it from the array?

**Comment by bernerdschaefer** [comment]
Good catch. It looks like it should be replaced with `Timeout::Error`, as is done for `HTTP_ERRORS` above it.

**Comment by sublimecoder** [comment]
Just submitted a PR to fix this issue. Had it show up in a few of my suspenders generated apps I've been upgrading to ruby 2.3.0.

**Comment by tute** [comment]
Thank you! Fixed with #688.
