### ISSUE TITLE
Pipelines: separate pipeline apps created

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/suspenders#689]
Hey guys,

Thanks for all your hard work on v1.35.0, it's come a long way since #617. Some nice touches added, especially running Heroku commands against staging as default!

However, when creating a new app the staging and production apps are generated as usual, but two pipeline apps are also generated instead of just the one. One has the staging app set as staging, the other has the production app set as production...

Thought I'd report this behaviour so we can start debugging. Ping #639. I'll try and take a look in the new year.

**Comment by rikkipitt** [comment]
Looks like the second pipeline command should be `add` rather than `create`.

```bash
         run  heroku pipelines:create jemcode -a jemcode-staging --stage staging --remote staging from "."
Creating jemcode pipeline... done
Adding jemcode-staging to jemcode pipeline as staging... done
         run  heroku pipelines:create jemcode -a jemcode-production --stage production --remote production from "."
Creating jemcode pipeline... done
Adding jemcode-production to jemcode pipeline as production... done
```

**Comment by zamith** [comment]
That seems correct to me. I'm creating a PR with that fix, and let's see what others have to say. Thanks.

**Comment by rikkipitt** [comment]
Cheers @zamith, I was noting this down to sort out next week but you beat me to it! I've had a quick check of your fixes, look good.

**Comment by zamith** [comment]
@rikkipitt Oh, sorry for that. I had some free time right now. :)

**Comment by rikkipitt** [comment]
No worries, at least one of us sorted it. It's a feature I've been anticipating for a while since Heroku announced Pipelines! Cheers!

**Comment by tute** [comment]
Thank you! Closing in favor of the related PR.
