### ISSUE TITLE
For API Deployments

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#698]
We've had a few projects recently that use rails API-only. Since [rails-api is merged into rails](https://github.com/rails/rails/pull/19832) (still coming soon), and [your guides now have recommendations in regards to API specs](https://github.com/thoughtbot/guides/pull/365), it might be worthwhile to add some flags to suspenders to automate those types of projects.

Would that be in-scope for suspenders?

**Comment by mcmire** [comment]
I would *love* it if you could use Suspenders to create an API-only app. An API app is more than just creating a Rails app with `--api-only`, though -- it's also the tools that help you build that API. And as far as I know, we have yet to come to agreement on what tools we would want (although I'm pretty sure those of us that have been on projects involving APIs have opinions).

So what I think we need first is to decide on a core set of tools. We discussed some of that in https://github.com/thoughtbot/guides/pull/365.

Internally, we create a card in a special Trello board we reserve for project experiments, and someone will try out a tool on a project for a while and report back later on whether the experiment was a success or failure. We probably need to go through some of the options that were mentioned in the PR above and do just that.

**Comment by tute** [comment]
As stated in https://github.com/thoughtbot/suspenders/issues/706, after https://github.com/thoughtbot/suspenders/pull/676, we'll be able to solve this with generators, which might live in a separate extension project. Will close this issue, and we can continue discussing in 706. Thanks!

**Comment by toobulkeh** [comment]
It sounds like JSON-API is the API Spec of choice for Thoughtbot then. Is that correct?

**Comment by tute** [comment]
> It sounds like JSON-API is the API Spec of choice for Thoughtbot then. Is that correct?

Replied in https://github.com/thoughtbot/suspenders/issues/706#issuecomment-220165560.

**Comment by anhari** [comment]
Maybe a dumb question, but can you explain what you mean by being able to solve this with generators?

**Comment by tute** [comment]
> Maybe a dumb question, but can you explain what you mean by being able to solve this with generators?

See PRs introducing behavior as generators:

- https://github.com/thoughtbot/suspenders/pull/767
- https://github.com/thoughtbot/suspenders/pull/676
