### ISSUE TITLE
Turn off CSS animations in test environment

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/suspenders#704]
CSS transitions can make it hard to test things, just like jQuery transitions.

We already turn off jQuery transitions with `$.fx.off = true`, and we should do the same for CSS.

In Haml:

```haml
- if Rails.env.test?
  :css
    * {
      transition-property: none !important;
      -webkit-transition-property: none !important;
    }
```

**Comment by gylaz** [comment]
Relevant PR: https://github.com/thoughtbot/suspenders/pull/705

**Comment by tute** [comment]
Thank you, Gabe! Should we close this issue in favor of the PR?
