### ISSUE TITLE
Installation error for Ruby 2.2.4 (requires Ruby version >= 2.2.3)

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/suspenders#707]
Hi guys i got a problem trying to install suspenders, i have ruby 2.2.4 and when i try to install suspenders this message appears:

ERROR:  Error installing suspenders:
	suspenders requires Ruby version >= 2.3.0.

Have no sense.
PD: kind of strange, have ruby 2.2.4 on fish and also on bash.
PDD: I use rbenv and have:
rbenv local --> 2.2.4
rbenv global --> 2.2.4
rbenv shell --> 2.2.4

Also on : ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

**Comment by mcmire** [comment]
You need to upgrade to Ruby 2.3.0 in order to install Suspenders.

**Comment by Xosmond** [comment]
Oh my god, sometimes the error is on your eyes. Sorry.
