### ISSUE TITLE
Streamline development setup

### ISSUE THREAD

**Issue by buren** [thoughtbot/suspenders#715]
I was trying to setup suspenders, to help out with #676, but ran into a few issues.

I ran `bin/setup`, then I had to manually install the below gems with `gem install`:

* `simple_form`
* `title`
* `quiet_assets`
* `capybara-webkit`
  * Needed to install `brew install qt`

not that it was a huge issue, but thought I would mention it since its wasn't documented anywhere. 

__Possible improvements__:

* Document in `README`
* Maybe an idea would be to just print it in `bin/setup` and mention the dependency on `qt`?
* Lastly those gems could be installed in `bin/setup, however:
  - `capybara-webkit`s dependency on `qt` is a problem (easily installed with `brew` in my case, but what about other systems? Detect the system an install accordingly seems perhaps a bit excessive?)
  - Installing global gems in`bin/setup` isn't perhaps a good idea

I'd be happy to do a PR for any of the above.

Thanks!

**Comment by tute** [comment]
Hi, thanks for your contribution!

I think they should be declared as development dependencies in the `suspenders.gemspec`, then the setup script would install them.

We can link to installation instructions for `qt` from `capybara-wekit`'s README: https://github.com/thoughtbot/capybara-webkit#qt-dependency-and-installation-issues.

Thank you, again!

**Comment by buren** [comment]
Created a PR for this at #717

**Comment by tute** [comment]
As your PR covers this issue, I'll close it in favor of #717. Thank you! :clap:
