### ISSUE TITLE
undefined method `halt_callback_chains_on_return_false=' when Rails 5 is installed

### ISSUE THREAD

**Issue by buren** [thoughtbot/suspenders#716]
After setting in the project for development I ran into a problem (how I set it up is described in more detail in #715.

When running the test suite I got:
```
undefined method `halt_callback_chains_on_return_false=' for ActiveSupport:Module (NoMethodError)
```

Same problem that @brandoncordell https://github.com/thoughtbot/suspenders/pull/671#issuecomment-172268118 seemed to have had, but I couldn't find if/how it was resolved.

While writing this issue, initially not knowing the root cause, I actually found it!

Rails 5 adds `halt_callback_chains_on_return_false` configuration option for newly generated apps, see [Railtie CHANGELOG](https://github.com/rails/rails/blob/master/railties/CHANGELOG.md).

The test suite generates a dummy_app, I guess, using the system version of Rails and since I have Rails 5.0.0.beta2 installed on my machine it generates with that option. Suspenders however doesn't target Rails 5 yet and tries to test against that app which contains that config option which isn't in Rails 4.

I'm not sure if its something that needs/has to be fixed, but thought this issue could at least act as documentation for others that might have Rails 5 installed and run into this.

Perhaps a fix could be to specify what version of rails is to be used, like `rails _4.2.5__ new`.

Thanks!

**Comment by brandoncordell** [comment]
Hey @buren. I wasn't able to find exactly what the issue was, but I fixed it on my machine by rebasing master (this was in my own fork of Suspenders) and then I had a `<app root>/tmp` directory that I needed to `rm`. After running the tests, does the `<app root>/tmp` directory persist?

**Comment by tute** [comment]
I have rails 5 too (`rails (5.0.0.beta1, 4.2.5.1, ...)`), and yet my command line uses the latest 4.2, so my tests run well.

Is this still an issue for you, @buren? How can I replicate it? Thank you for reporting.

**Comment by buren** [comment]
hm, interesting I'm not really sure. @tute whats your output when running `rails -v` in the terminal? (mine is Rails 5.0.0.beta2..).

**Comment by tute** [comment]
> @tute whats your output when running rails -v in the terminal? (mine is Rails 5.0.0.beta2..).

```
% gem list | grep rails
[...]
rails (5.0.0.beta1, 4.2.5.1, 4.2.5, 4.2.4)
% rails -v
Rails 4.2.5.1
```

**Comment by buren** [comment]
hm interesting.. mine is

```
% gem list | grep rails
[...]
rails (5.0.0.beta2, 4.2.5.1, 4.2.5, 4.2.0)
% rails -v
Rails 5.0.0.beta2
```

I wonder why `rails -v` for me outputs `Rails 5.0.0.beta2`, while yours is `4.2.5.1`..

**Comment by tute** [comment]
I just got a different error:

```
suspenders master % rm -rf tmp
suspenders master % rails -v
Rails 5.0.0.beta3
suspenders master % rake
/Users/tutec/.rbenv/versions/2.3.0/bin/ruby -I/Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/lib:/Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-support-3.4.1/lib /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Randomized with seed 61714
.../Users/tutec/Sites/opensource/suspenders/suspenders/tmp/dummy_app/config/environments/development.rb:61:in `block in <top (required)>': uninitialized constant ActiveSupport::EventedFileUpdateChecker (NameError)
[...]
```
Making suspenders create a rails application with the proper version would be a fix indeed.

**Comment by tute** [comment]
Closing this issue, as it doesn't look like it bothered other people, and it almost never did to me. Thanks!

**Comment by BKSpurgeon** [comment]
any solution to this one? when i'm running tests one moment all is well - i then create another rails application in a different folder and now all of a sudden i'm getting the same error.

**Comment by ValZapod** [comment]
apt-get purge  dradis

apt-get install dradis 


works great.
