### ISSUE TITLE
switch to babel-transpiler and sprockets 4

### ISSUE THREAD

**Issue by iDuuck** [thoughtbot/suspenders#726]
why not switching to the `babel-transpiler` gem with sprockets version 4?

**Comment by tute** [comment]
cc @MattMSumner

**Comment by MattMSumner** [comment]
I followed the instructions from babel itself https://babeljs.io/docs/setup/#rails. I can checkout `babel-transpiler` on Friday to see if it makes sense to switch.

**Comment by tute** [comment]
@iDuuck why do you think we should switch to `babel-transpiler`? Thank you!

**Comment by tute** [comment]
@MattMSumner @iDuuck do we need to work on anything for this? Id there anything else we should discuss?

**Comment by iDuuck** [comment]
[The official rails repositories update guide to the newer sprockets](https://github.com/rails/sprockets/blob/master/UPGRADING.md#es6-support) said that `babel-transpiler` is the way to go with Rails. Don't know if this is better than `sprockets-es6`.

As far as I can read from this README, the only thing that needs to be done for this, is to add the `babel-transpiler` gem to the Gemfile

**Comment by MattMSumner** [comment]
> Sprockets 4 ships with a babel processor

It looks like this is currently in beta2. As soon as a stable release come out I'll open a PR to change this.

Thanks @iDuuck for pointing this out.

**Comment by tute** [comment]
@MattMSumner do you think it's ok to apply this fix while sprockets is in beta? I think it's better than the myriad deprecation messages that appear if you add ES6 files to a new suspended project. Thanks!

**Comment by iDuuck** [comment]
I just found out, that this is possible (and used by [this](http://9elements.com/io/) company for the clients):

*The `.babelrc` needs to be there and all needed packages in `package.json` (`babel-core` and plugins)

Gemfile:
```ruby
gem 'sprockets', '4.0.0.beta2'
gem 'babel-transpiler'
gem 'sprockets-commoner'
```

app/assets/config/manifest.js
```js
//= link_tree ../images
//= link_directory ../javascripts .js
//= link_directory ../stylesheets .css
```

[Read more...](http://9elements.com/io/index.php/babel-rails-5-and-sprockets-4/)

**Comment by MattMSumner** [comment]
@tute you might be right. Alternatively do you think I should remove babel entirely and have suspenders setup without a default until sprockets ships?

@iDuuck thanks for the link. I'm not sure I want to remove the asset pipeline entirely in favor of webpack by default.

I'll have some time on Friday to open a couple of PRs and spark more conversation.

**Comment by composerinteralia** [comment]
Suspenders is now on Rails 6, which uses webpacker for JS, so I think this issue is no longer relevant.
