### ISSUE TITLE
Problems wth burbon and bitters

### ISSUE THREAD

**Issue by dixpac** [thoughtbot/suspenders#727]
Hi,
I have some problems with suspenders generated app. When I generate new app and try to render my view I got this error 
![screen shot 2016-03-12 at 14 13 32](https://cloud.githubusercontent.com/assets/7427365/13723200/1a2302e2-e85e-11e5-95f2-59d37bf94493.png)
When I change my @import to "base/base", I get this error
![screen shot 2016-03-12 at 14 25 55](https://cloud.githubusercontent.com/assets/7427365/13723206/5d401f38-e85e-11e5-885b-4849503b3b90.png)

Only way I was able to solve issue was, to update bourbon to version **5.0.0.beta3** and use `@import 'base/base'` instead of `'base/grid-settings'`. Although I'm not sure will my grid system work now :(

Here is my test repo with 2 commits first not working, second working
https://github.com/dixpac/test_app/commits/master

**Comment by tute** [comment]
https://github.com/thoughtbot/suspenders/pull/718 solved this issue. If I don't get to it earlier, next week we'll do a release and this will be fixed. Thanks for reporting.

**Comment by tute** [comment]
Is this still an issue in latest release, @dixpac? Thank you!

**Comment by jcmorrow** [comment]
@tute I just started a new app and my smoke test is failing with: 

     File to import not found or unreadable: base/base.
    ./app/assets/stylesheets/application.scss:8

I think it's related but I'm not sure. If not I can open up a separate issue.

**Comment by dixpac** [comment]
@tute works like a charm for me now :+1:

**Comment by dixpac** [comment]
@jcmorrow I have a feeling that you have some problems with _bitters_, maybe you should open separate issue. Do you have `app/assets/stylesheets/base` dir created?

**Comment by tute** [comment]
Thanks, @dixpac! Closing now, can continue discussion until yours works, @jcmorrow.

**Comment by jcmorrow** [comment]
@dixpac Nope, I don't have an `app/assets/stylesheets/base` directory. I wouldn't be surprised if I was missing something obvious here.

**Comment by jcmorrow** [comment]
@tute I started another project and didn't need to run the bitters install manually, which was interesting. Also, we just had an issue on CircleCI because of the bourbon upgrade, but going back to 4.2.6 fixed it. It looks like from the latest bourbon [release notes](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.beta.4) that 5.0.0.beta3 was supposed to be considered prerelease, should we revert back to 4.2.6 in suspenders?

**Comment by dixpac** [comment]
@jcmorrow suspenders should **automatically** generate bitters assets, I didn't have problem with this. I'm afraid if we downgrade bourbon to 4.2.6 then we will have same problem as described in issue. I basically can't render view until upgrade to 5.0.0.beta3! 
What was the issue on CircleCI ?

maybe @tute can have some idea ?

**Comment by jcmorrow** [comment]
@dixpac I believe suspenders didn't generate the bitters assets the first time I installed because I didn't have the bitters gem installed on my machine, at least that's my theory. I'm not sure if suspenders can remedy that or not. 

Using 5.0.0.beta.3 CircleCI failed with `ActionView::Template::Error: File to import not found or unreadable: bourbon`. We ended up just reverting to Bourbon 4.2.6.

**Comment by tute** [comment]
> I believe suspenders didn't generate the bitters assets the first time I installed because I didn't have the bitters gem installed on my machine, at least that's my theory. I'm not sure if suspenders can remedy that or not.

https://github.com/thoughtbot/suspenders/pull/732#issuecomment-198181368 might be related with this, and if not we should probably take this into account as part of that PR or a new one. suspenders should make sure all dependencies are installed, while developing suspenders itself and while generating apps.

> Using 5.0.0.beta.3 CircleCI failed with ActionView::Template::Error: File to import not found or unreadable: bourbon. We ended up just reverting to Bourbon 4.2.6.

@tysongach might have context on this issue.

**Comment by tysongach** [comment]
@jcmorrow @tute I just saw a similar issue on Circle yesterday and am looking into that; hopefully today or at least by Friday.

**Comment by tysongach** [comment]
@jcmorrow I just released Bourbon `5.0.0.beta.5` which should resolve this issue.

**Comment by dixpac** [comment]
@tysongach nice, I converted my project from beta.3 to beta.5 and everything works fine.
I took a liberty and created PR to update suspenders to Bourbon 5.0.0.beta.5, if that is ok with @tysongach  @tute 
https://github.com/thoughtbot/suspenders/pull/737

**Comment by tute** [comment]
Thank you, Tyson and everyone!
