### ISSUE TITLE
Simple Form is not configured by default

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/suspenders#728]
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration

    .[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple
    /home/lorentrogers/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined meth
      from /home/lorentrogers/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path
      from /home/lorentrogers/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/gems/bitters-1.3.1/lib/bitters.rb:1:in `<top (required)>'
      from /home/lorentrogers/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
      from /home/lorentrogers/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/gems/bitters-1.3.1/bin/bitters:3:in `<top (required)>'
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/bin/bitters:23:in `load'        
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/bin/bitters:23:in `<main>'   
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
      from /home/lorentrogers/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

These errors don't seem to affect the test suite though:

    Finished in 3 minutes 12 seconds (files took 0.23542 seconds to load)
    39 examples, 0 failures

**Comment by lorentrogers** [comment]
Possibly related to #717

**Comment by tute** [comment]
It makes sense that at least once they happen. See https://github.com/thoughtbot/suspenders/pull/643#issue-113134438.

**Comment by tute** [comment]
This issue should be tackled in simple_form itself. See https://github.com/plataformatec/simple_form/issues/1316. Will close this issue here. Thank you very much for reporting.
