### ISSUE TITLE
Logs are missing (possible Puma+Quiet Assets interaction?)

### ISSUE THREAD

**Issue by sumeetjain** [thoughtbot/suspenders#735]
Is it desired behavior for logs to not show for a Rails application generated by Suspenders? With a fresh application, running `heroku local` correctly serves the application, but no logs show in Terminal. But they do show in development.log, as one would expect.

I found https://github.com/evrone/quiet_assets/issues/40, which suggests a possible interaction between Puma and Quiet Assets. But when I run `rails s` (as opposed to `heroku local`) on a new Suspenders-generated application, the logs _do_ show–and Puma is still being used. Could there be some side effect of using forego?

I'm not even sure this is even a true issue. It's possible y'all prefer to only have logs in development.log, but I wanted to confirm before spending more time debugging this.

**Comment by mike-burns** [comment]
We do want logs in production, and I have not seen problems like this on Heroku. Do you see them on Heroku, or only in `heroku local`?

**Comment by tute** [comment]
> Do you see them on Heroku, or only in `heroku local`?

ping @sumeetjain for that question ^

**Comment by sumeetjain** [comment]
At least on my computer, this is a problem locally. Here's the script I followed to test it:

```bash
➜  Code gem install suspenders
Fetching: bitters-1.3.1.gem (100%)
Successfully installed bitters-1.3.1
Fetching: suspenders-1.38.1.gem (100%)
Successfully installed suspenders-1.38.1
2 gems installed
➜  Code suspenders do_logs_show
[truncated]
➜  Code cd do_logs_show
➜  do_logs_show git:(master) ✗ rails g scaffold user name
Running via Spring preloader in process 60568
[truncated]
➜  do_logs_show git:(master) ✗ bundle exec rake db:migrate
== 20160428225518 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0073s
== 20160428225518 CreateUsers: migrated (0.0074s) =============================

➜  do_logs_show git:(master) ✗ heroku local
```

Then I navigated to **/users** and clicked through the application to make a new user. I expected some kind of output in the terminal, but nothing changed there at all. However, logs/development.log does reflect the correct actions. It just wasn't tailed to terminal.

**Comment by mike-burns** [comment]
Can you try that again, but with the `rails_stdout_logging` gem? So after the `cd do_logs_show` step, add that gem to the `Gemfile`, bundle, and then see if that changes anything.

**Comment by sumeetjain** [comment]
That does change things. However–and maybe this is unrelated or another issue–I am seeing a Rack app error in the logs. Here's a cut from the logs where the Rails logs I'm expected do show, but then there is the unexpected Rack app error:

```
10:11:18 AM web.1 |  Started GET "/users" for 127.0.0.1 at 2016-04-29 10:11:18 -0500
10:11:18 AM web.1 |  Processing by UsersController#index as HTML
10:11:18 AM web.1 |    User Load (0.3ms)  SELECT "users".* FROM "users"
10:11:18 AM web.1 |    Rendered users/index.html.erb within layouts/application (3.0ms)
10:11:18 AM web.1 |    Rendered application/_flashes.html.erb (0.6ms)
10:11:18 AM web.1 |    Rendered application/_analytics.html.erb (0.5ms)
10:11:18 AM web.1 |    Rendered application/_javascript.html.erb (9.6ms)
10:11:18 AM web.1 |    Rendered application/_css_overrides.html.erb (0.5ms)
10:11:18 AM web.1 |  Completed 200 OK in 34ms (Views: 32.5ms | ActiveRecord: 0.3ms)
10:11:18 AM web.1 |  2016-04-29 10:11:18 -0500: Rack app error: #<NoMethodError: undefined method `[]' for nil:NilClass>
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/lo…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:24…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/midd…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `cal…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/ca…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/midd…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `c…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:1…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/newrelic_rpm-3.15.2.317/lib/new_relic/age…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:224:…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:569:in `han…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:406:in `pro…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.4.0/lib/puma/server.rb:271:in `blo…
10:11:18 AM web.1 |  /Users/sumeetjain/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in…
```

Maybe there's something unique about my machine? I stick pretty close to Thoughtbot's setup (e.g. I use a mostly-unmodified version of thoughtbot/laptop), so I wouldn't have thought I'd have [m]any local setup idiosyncrasies.

**Comment by tute** [comment]
> Can you try that again, but with the rails_stdout_logging gem? So after the cd do_logs_show step, add that gem to the Gemfile, bundle, and then see if that changes anything.

This is related with: https://github.com/thoughtbot/suspenders/pull/604#issuecomment-143247939. We could set up `suspenders` apps ready for heroku, even if we don't automatically deploy it there at first.

---

@sumeetjain I've never seen that stacktrace, will try to trigger it in my computer.

**Comment by tute** [comment]
Following the steps you describe in https://github.com/thoughtbot/suspenders/issues/735#issuecomment-215590370 (and adding the stdout logging gem) I can't replicate your stacktrace.

**Comment by sumeetjain** [comment]
> This is related with: #604 (comment). We could set up suspenders apps ready for heroku, even if we don't automatically deploy it there at first.

Having reviewed that issue, that sounds great.

> Following the steps you describe in #735 (comment) (and adding the stdout logging gem) I can't replicate your stacktrace.

No problem–I'll dig into it on my own. Probably something unique to my machine.

**Comment by mike-burns** [comment]
https://blog.heroku.com/archives/2016/5/2/container_ready_rails_5#stdout-logging - when we switch Suspenders to Rails 5, logging will happen automatically on Heroku -- and perhaps on `heroku local`, too.

**Comment by tute** [comment]
Closing this issue in favor of PR #756 that will take care of this.

As Mike states, in Rails 5 this won't be an issue, regardless of our code.

Thank you for reporting, @sumeetjain.
