### ISSUE TITLE
Error loading SASS file in fresh project

### ISSUE THREAD

**Issue by rdavila** [thoughtbot/suspenders#740]
I'm using version `1.37.0` and just got the following error:

![screen shot 2016-03-27 at 6 57 37 pm](https://cloud.githubusercontent.com/assets/9183/14068604/1d918948-f44e-11e5-80da-48ee262ff142.png)

**Comment by tute** [comment]
Hey, thanks for reporting! This was fixed in https://github.com/thoughtbot/suspenders/pull/737 (opened after https://github.com/thoughtbot/suspenders/issues/727), now merged into master. Will be fixed in next suspenders release. Thanks!
