### ISSUE TITLE
Bullet error on master

### ISSUE THREAD

**Issue by johnpaulashenfelter** [thoughtbot/suspenders#744]
Steps:

* `git clone...`
* `bundle`
*  `bundle exec suspenders ../suspenders-latest`

```
Bitters files installed to app/assets/stylesheets/base/base
Install Refills
    generate  refills:import
/Users/johnpaul/craft/suspenders-latest/config/environments/development.rb:19:in `block (2 levels) in <top (required)>': uninitialized constant Bullet (NameError)
```

The gem is there, its bundled. Maybe there's a problem with the environment or something with the refills step?

**Comment by tute** [comment]
Yes, suspenders' dependencies need work. See an open PR and linked issues: https://github.com/thoughtbot/suspenders/pull/732#issuecomment-198178443.

I'd love to get that moving along. Thank you for reporting.

**Comment by tute** [comment]
A workaround for now is initialize a project, run bundle on it, and then work on suspenders-itself.
