### ISSUE TITLE
Suspenders 1.38.0 bourbon/refills/neat dependencies

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/suspenders#748]
Hey guys,

The last few versions of suspenders have been fraught with out of the box SCSS issues. I've just installed the latest suspenders (v1.38.0) and the latest issues are with your refills. Version 0.1.0 of refills is using deprecated mixins... E.g. the modal is using transitions/buttons (since removed in master).

Is there a trick to install the latest of everything to ensure everything works at any given point in time?

Cheers for the support, really love Suspenders but it's been getting harder and harder to get up and running quickly these days as it once was.

Rikki

**Comment by tute** [comment]
Thanks for pointing this out, @rikkipitt. I'll add two tasks for this issue:

- [ ] Add a test or script to generate a scaffold in a suspenders generated app, to verify it loads properly (now it does not, see attached screenshot)
- [ ] Pair with @tysongach to streamline these bugs, and release 1.39

<img width="727" alt="screen shot 2016-04-20 at 1 56 05 pm" src="https://cloud.githubusercontent.com/assets/54260/14684840/d29f8376-06ff-11e6-800f-8d1cfaa698e6.png">

**Comment by rikkipitt** [comment]
Cheers @tute I'm sure you'll iron out these update issues soon.

**Comment by tute** [comment]
Just published a 1.38.1 bugfix release. Thanks for reporting.

**Comment by rikkipitt** [comment]
Brilliant, thanks a lot! I'll give this a whirl shortly.
