### ISSUE TITLE
Pull request template?

### ISSUE THREAD

**Issue by jessieay** [thoughtbot/suspenders#755]
Would it make sense to include a pull request template in suspenders apps? https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

My worry with pull request templates is that people will begin to rely on them rather than focusing on creating good commit messages, but it's also nice to have pull request templates, especially for anything open source. Could also have a meta template for the suspenders repo itself...

**Comment by mike-burns** [comment]
I'm certainly not opposed. OTOH, we haven't had a problem with PRs in this particular repo. If someone makes a PR to add one, I won't complain.

**Comment by tute** [comment]
I don't see how could we get better pull requests by providing a template. @jessieay do you have a concrete suggestion? Thanks for your input!

**Comment by jessieay** [comment]
Hello!

I was **actually*  wondering if suspenders-based projects would want a default pull request template included on genrate. Although it might make sense to add the template to this repo, too,

In a world where everyone is squashing commits and submitting one commit per PR, using this commit message format would auto-populate the pull request fields with good info: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

In a situation where there are multiple commits, people might now know about or be on the same page about what info should be included in a pull request title / description. In that case, you may end up with a PR like this: https://github.com/thoughtbot/dotfiles/pull/334

This is most important for open source projects (like Suspenders) but may also be helpful for anyone using the suspenders generator for their project.

Best course of action may be to try using pull request templates on some open source projects and see if it is helpful or harmful.

**Comment by mike-burns** [comment]
Oh, interesting idea! I wonder which of our projects is using a PR template.

These are the ones I know about that have an `ISSUE_TEMPLATE.md`, which is slightly different:

- https://github.com/thoughtbot/Argo
- https://github.com/thoughtbot/ember-cli-rails

A quick skim of Argo shows great issue reports:

- https://github.com/thoughtbot/Argo/issues/368
- https://github.com/thoughtbot/Argo/issues/370
- https://github.com/thoughtbot/Argo/issues/372
- https://github.com/thoughtbot/Argo/issues/374

And some issues that ignored the template: https://github.com/thoughtbot/Argo/issues/371 and https://github.com/thoughtbot/Argo/issues/369

Similar story on ember-cli-rails:

- https://github.com/thoughtbot/ember-cli-rails/issues/451
- https://github.com/thoughtbot/ember-cli-rails/issues/446
- https://github.com/thoughtbot/ember-cli-rails/issues/438

I'm not sure of any thoughtbot projects that use a `PULL_REQUEST_TEMPLATE` file, or actually any other project that does. Does anyone else have an example? I'm curious what it would look like, and whether people are following it.

**Comment by jessieay** [comment]
An open source project I maintain has a PR template: https://github.com/18F/dolores-landingham-bot/blob/master/PULL_REQUEST_TEMPLATE.md

Pretty new so don't have a ton of data, but the most recent PR from an outside contributor had all the right info: https://github.com/18F/dolores-landingham-bot/pull/174

I imagine a thoughtbot template might be slightly different. Anyway, feel free to close if this feels too early. 🌈

**Comment by mike-burns** [comment]
That was a great example of it working. Just the `Changes proposed in this pull request` prompt seems like a useful thing to put in such a template.

I stand my by first comment: I'm not feeling any pain that would be solved by this, but I would gladly look at/give a thumbs-up to a PR that added one.

@tute I leave the fate of this issue to you.

**Comment by tute** [comment]
I think for suspenders-itself we don't need this, as contributions are typically (and thankfully) very high quality.

For generated projects, in my experience a template would depend on the team. Is it a big or a small team behind the generated project? Do they pair, how do they use git and GitHub right now? Do they need to link to JIRA/Trello/other issue tracker? I don't think I can come with a good generic template. For the suspenders projects I work on, PRs being blank is good because the commit message is already good, and people open up PRs with hub, which grabs that content for the PR title and description. When they are not good, you notice the blank screen while creating the PR, notice that you need to describe it, and do it in the commit message itself, saving time for the upcoming rebase and squash.

I vote for a "no" on this now, and will close this issue. If many people see value in this change, let's reconsider and work on it. Thanks for opening this up, @jessieay! :)

**Comment by mike-burns** [comment]
Oh! I had forgotten about but would now like to mention: https://github.com/thoughtbot/templates

As we write these things, we should put something in there.
