### ISSUE TITLE
Ensure all production-necessary services are configured before boot

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#757]
Suspenders should give developers visibility around production-necessary services configuration, and let them know if any is missing configuration.

Right now for example, we can successfully test and deploy suspenders apps without configuring Skylight. See:

> If we think monitoring is required and we think skylight is the tool for that, then should we make it impossible to deploy without it? That was my thinking by suggesting the configuration file. While It's not _needed_, I think it is possible to use one and would let us use `ENV.fetch` so we get errors if we forget to set it up.

and 

> [...] a pull request that ensures all production-necessary services are configured and refusing to boot if they aren't
> 
> https://github.com/thoughtbot/suspenders/pull/692#issuecomment-216238298.

**Comment by mike-burns** [comment]
Cool idea. Might be out of scope for Suspenders.

Going to close this and continue the discussion on a PR.
