### ISSUE TITLE
Heroku pipelines plugin not required

### ISSUE THREAD

**Issue by blackjid** [thoughtbot/suspenders#758]
The heroku pipelines plugin is now part of the heroku cli. It comes bundled, so there is no need to install it. It also doesn't show up when calling `heroku plugins` so making suspenders exit prematurely.

https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/adapters/heroku.rb#L62-L66

We had this problem in potassium where we inspired our heroku app bootstrapping in suspenders... ;)
https://github.com/platanus/potassium/pull/88

**Comment by tute** [comment]
aha! Thanks for reporting. I'd like to support both versions.

Would you send a PR fixing this? Thanks again!

**Comment by tute** [comment]
Fixed in PR.

**Comment by tute** [comment]
Fixed in commit https://github.com/thoughtbot/suspenders/commit/ac36c65f1f9c33fcabb43e81c30b5ebb928665b0
