### ISSUE TITLE
Set up explicit staging env for Honeybadger

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#759]
After https://github.com/thoughtbot/suspenders/pull/743 suspender's staging servers run on production environment. This means that Honeybadger will log every exception as happening in production, whether it happens in staging or production.

Suspenders should explicitly set the `env:` option in Honeybadger's [config file](http://docs.honeybadger.io/lib/ruby.html). We can infer the Heroku stage from `HEROKU_APP_NAME`, or manually define a `STAGE` environmental variable to use in Honeybadger (and other services when needed).

**Comment by tute** [comment]
@pablobm does your "Avoid using the Heroku add-on" guideline relate with this? Thanks!

**Comment by pablobm** [comment]
@tute Oh, actually no. I had no idea of this issue.

**Comment by blackjid** [comment]
@tute we built this gem to get the current pipeline environment from heroku inferring it from `HEROKU_APP_NAME` and adding some sugar.
https://github.com/platanus/heroku-stage

We've been using it to set environment on monitoring services like sentry

**Comment by toobulkeh** [comment]
This was completed https://github.com/thoughtbot/suspenders/commit/675d2cee9118712b9bac7066ce989cfcba791cf4

**Comment by nickcharlton** [comment]
I'm going to close this issue, as it seems we solved it from @toobulkeh's comment.
