### ISSUE TITLE
Generate `bin/setup_heroku` script

### ISSUE THREAD

**Issue by tute** [thoughtbot/suspenders#763]
Commands will be something like:

```
heroku create dummy-app-staging --remote staging
heroku create dummy-app-production --remote production
heroku config:add RAILS_SERVE_STATIC_FILES=true --remote staging
heroku config:add RAILS_SERVE_STATIC_FILES=true --remote production
heroku config:add SECRET_KEY_BASE=? --remote staging
heroku config:add SECRET_KEY_BASE=? --remote production
heroku config:add APPLICATION_HOST=dummy-app-staging.herokuapp.com --remote staging
heroku config:add APPLICATION_HOST=dummy-app-production.herokuapp.com --remote production
heroku pipelines:create dummy-app -a dummy-app-staging --stage staging --remote staging
heroku pipelines:add dummy-app -a dummy-app-production --stage production --remote production
```

This will make it easy to deploy any project to Heroku using staging and production environments, and Heroku Pipelines (whether they have been generated by suspenders –and with the heroku flag set– or not).

**Comment by emars** [comment]
This would be a sweet feature. 

I currently have a suspenders that I'm using that I did not specify the `--heroku` flags for.

When I went to deploy to heroku it's missing a ton of env variables.

**Comment by mike-burns** [comment]
This seems to be something more in scope for [parity](https://github.com/thoughtbot/parity).
