### ISSUE TITLE
Heroku:Pipelines now a core plugin?

### ISSUE THREAD

**Issue by rikkipitt** [thoughtbot/suspenders#764]
I've updated my system and it appears the Heroku Pipelines plugin is now part of the core toolbelt. I need to confirm that, but the build exits when it can't grep the piplelines plugin.

```bash
heroku plugins:install heroku-pipelines
Not installing heroku-pipelines because it is already installed as a core plugin.
```

**Comment by tute** [comment]
That is right, thanks for reporting. Also reported in https://github.com/thoughtbot/suspenders/issues/758.

**Comment by tute** [comment]
This is the condition that we should fix in order to make this work for people with newer and older versions of the `heroku` command:

https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/adapters/heroku.rb#L54-L58

**Comment by rubylibre** [comment]
Is using `heroku help | grep pipelines` an option to work from?

**Comment by tute** [comment]
Not sure. Will it work on both newer and older versions of the toolbelt?

**Comment by rubylibre** [comment]
After some searching:

This did not change: 
https://github.com/heroku/heroku-pipelines/blob/6cb73973e2cd72ad2cea5eb9812f5a7eafd81beb/index.js#L7

When the plugin became part of the cli (general available):
https://github.com/heroku/heroku-pipelines/commit/08915b80cb7b7b62cb0cf87a9724df48d6a0802d
https://github.com/heroku/cli/commit/e026f854a0f981d4ac0ee34feeafa9589fc60e2f

**Comment by tute** [comment]
Closing in favor of PR: https://github.com/thoughtbot/suspenders/pull/772. Thank you!
