### ISSUE TITLE
--skip-spring and spring stop

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/suspenders#771]
As reported in https://github.com/thoughtbot/suspenders/commit/3cf23ed37a94a890f7678a8ec5cd072385f93bb4#commitcomment-17641783 : `suspenders --skip-spring` is now broken. We need to make sure a test exists to catch this regression.

**Comment by mike-burns** [comment]
@pasco `templates/Gemfile.erb` has this hardcoded in it:

```ruby
group :development do
  gem "spring"
  gem "spring-commands-rspec"
end
```

As such, `bin/spring` will always be generated and available, regardless of whether `--skip-spring` is passed. Are you seeing something else? Do you have a way to reproduce a bug?

**Comment by tute** [comment]
`--skip-spring` is not an option in current suspenders, so this is not a bug. Thanks!
