### ISSUE TITLE
Refills / Bourbon Conflict.

### ISSUE THREAD

**Issue by aaronthewhite** [thoughtbot/suspenders#779]
Ran a command:

``` Shell
$ rake assets:precompile            
rake aborted!
Sass::SyntaxError: File to import not found or unreadable: refills/flashes.
```

Saw: 

> Bourbon 4 (Refills is not currently compatible with Bourbon 5)

Tried to downgrade bourbon to `~> 4.2`

``` Shell
$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
You have requested:
  bourbon ~> 4.2

The bundle currently has bourbon locked at 5.0.0.beta.5.
Try running `bundle update bourbon`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

``` Shell
$ bundle update bourbon
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies....
Bundler could not find compatible versions for gem "bourbon":
  In Gemfile:
    bourbon (~> 4.2)

    suspenders was resolved to 1.39.0, which depends on
      bitters (~> 1.3) was resolved to 1.3.1, which depends on
        bourbon (>= 5.0.0.beta.3)

    neat (~> 1.7.0) was resolved to 1.7.4, which depends on
      bourbon (>= 4.0)
```

**Comment by tute** [comment]
Does the fix in master work for you? See https://github.com/thoughtbot/suspenders/commit/60d7bc5f4109824d1a1b95b6ebd45d7702b7aa62. If so, I'll prepare a new release. Thanks!

**Comment by aaronthewhite** [comment]
It does, thanks. =]

**Comment by aaronthewhite** [comment]
Spoke too soon. `rake assets:precompile` still failed.

**Comment by tute** [comment]
cc @tysongach for your input on how we might work this out. Thank you in advance!

**Comment by tysongach** [comment]
This might be an issue with Neat, rather than Refills.

- We actually [_just_ removed the Bourbon dependency in Neat](https://github.com/thoughtbot/neat/commit/441549048f59b2cc8264e4a5a4496f9e934d69ef) last week, but haven’t cut a release yet. You could pull from `master` to test that assumption.
- While Refills does claim a Bourbon 4 dependency, the flashes partial specifically works with 4 or 5.

**Comment by tysongach** [comment]
[This PR](https://github.com/thoughtbot/suspenders/pull/780) may help.

**Comment by tute** [comment]
Tyson merged his fix into master (thank you, Tyson!).

@aaronthewhite, does this help with your issue?

**Comment by aaronthewhite** [comment]
Apparently I was being affected by [issue #64 of skylight](https://github.com/skylightio/skylight-ruby/issues/64). Using the workaround allowed me to bundle install, but the refills/flashes were not generated as part of the suspenders install process because of the failing bundle. After using the workaround for skylight, deleting the repo and generating a new app with suspenders fixed everything.

**Comment by tute** [comment]
Thanks!
