### ISSUE TITLE
Auto-Generate & Deploy SSL for staging and production

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#781]
With the [advent of Free SSL endpoints on Heroku](https://blog.heroku.com/archives/2016/5/18/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours) and [Free SSL certificates using LetsEncrypt](https://letsencrypt.org/), Suspenders would be the ideal place to automatically configure and setup SSL certificates as part of all new rails applications -- even for both staging and production environments.

So far, we've configured applications thusly:
1. Deployed [Sabayon](https://github.com/dmathieu/sabayon) applications (a small Go app that gains Heroku permissions) for each environment app. We've done this using the naming scheme `sabayon-<app>-staging` and `sabayon-<app>-production`
2. Added the following config to rails' `config/routes.rb`:
   
   > ``` ruby
   > Rails.application.routes.draw do
   >   # Let's Encrypt for Sabayon (Heroku)
   >   if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
   >     get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN"] }" => proc { [200, {}, [ ENV["ACME_KEY"] ] ] }
   >   else
   >     ENV.each do |var, _|
   >       next unless var.start_with?("ACME_TOKEN_")
   >       number = var.sub(/ACME_TOKEN_/, '')
   >       get ".well-known/acme-challenge/#{ ENV["ACME_TOKEN_#{number}"] }" => proc { [200, {}, [ ENV["ACME_KEY_#{number}"] ] ] }
   >     end
   >   end
   > ...
   > ```
3. Forced SSL in Staging and changed ASSET_HOST to be protocol specific.  
4. Setup `bin/setup` to properly check for the sabayon apps.

Open questions we still have:
1. What is the best user/account strategy with Heroku to use the API KEY for Sabayon. We've created separate accounts for each client and have silo'd access using those keys -- which are not the same key. Heroku cloud now supports teams (like Enterprise) though there is no free tier of this.
2. We need help automating the deployment of the Sabayon apps. This includes the app names, keys, timeout periods, and domains.
3. Is this a separate generator / flag, since it includes information not previously required, or info that may be optional (like domain names)?

Hopefully this is close-enough to discuss. If it seems worthwhile, I'd be happy to contribute to the PR.

🍻 to an automated, secure, web.

**Comment by tute** [comment]
I haven't yet deployed any app using these options yet, but I'd love to have it baked into suspenders. I will not have time for a couple of months to spike on this though. Thanks for your contribution!

**Comment by HintikkaKimmo** [comment]
I am definitely going to test this next week. Exactly what I need to figure out how to do anyway. Thanks @toobulkeh

**Comment by tute** [comment]
Thanks @HintikkaKimmo! Please let us know how it went. Would either of you be willing to send over a PR addressing this?

**Comment by toobulkeh** [comment]
I'd be happy to put this together.

Note that we changed those ugly routes to a middleware, which allows us to easily use `config.force_ssl = true` in both staging and production environments.

For future reference, here's the middleware code we're using, thanks to the Heroku team:

```ruby
# config/initializers/sabayon.rb
require "sabayon_middleware"

Rails.application.config.middleware.insert_before 0, SabayonMiddleware
```

```ruby
# lib/sabayon_middleware.rb
class SabayonMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    data = []
    if ENV['ACME_KEY'] && ENV['ACME_TOKEN']
      data << { key: ENV['ACME_KEY'], token: ENV['ACME_TOKEN'] }
    else
      ENV.each do |k, v|
        if d = k.match(/^ACME_KEY_([0-9]+)/)
          index = d[1]
          data << { key: v, token: ENV["ACME_TOKEN_#{index}"] }
        end
      end
    end

    data.each do |e|
      if env["PATH_INFO"] == "/.well-known/acme-challenge/#{e[:token]}"
        return [200, { "Content-Type" => "text/plain" }, [e[:key]]]
      end
    end

    @app.call(env)
  end
end
```

This does add an extra middleware step to every request in your app -- but it's needed for the force_ssl config (because these requests need to happen over HTTP on initial and renewal requests)

Hope this helps.

**Comment by HintikkaKimmo** [comment]
Mine did not work the first time so round 2 on Sunday. However, I think I was running into LetsEncrypt issue rather than suspenders or rails issue. @toobulkeh if you have something ready put PR for this I am building this for a side project and having some time constraints at the moment.

**Comment by dijonkitchen** [comment]
Since Heroku SSL is free only under a paid plan, won't it break usage for people only on a free Heroku dyno? 

Also, would it be necessary to have the Let's Encrypt certificate work in staging?

**Comment by toobulkeh** [comment]
Sorry for the delay (I didn't have notifications turned on).

@dijonkitchen -- Good points. So maybe using this as a config flag would make more sense than a default?

As far as staging goes -- we subscribe to the belief that staging and production should be as similar as possible. With Sabayon, this requires an additional app per environment to manage -- which is a bit overkill and config creep, but worthwhile IMO.

I'll leave it up to thoughtbot to decide what's best for suspenders.

In related news, [here is another approach](https://github.com/KMarshland/heroku-ssl) using heroku CLI commands and a free redis addon per app env. I like this approach better than a separate web dyno, despite the security differences, but it's [not recurring yet](https://github.com/KMarshland/heroku-ssl/issues/3#issuecomment-279780614).

**Comment by dijonkitchen** [comment]
Yeah @toobulkeh, I think a flag would be better. 

For staging, I agree that it should be as similar to production as possible to detect errors earlier. But for the SSL certificates, my understanding was that you'd need a custom domain. If that's the case, wouldn't the staging environment also need a custom domain? I figure most people would have a custom domain for just their production environment because of cost or just necessity. 

The heroku_ssl gem seems really interesting, so I'll have to keep tabs on it. Thanks!

**Comment by toobulkeh** [comment]
In general, I'm waiting to see what Heroku releases to support this -- as it'll be the only way to fully automate it.

**Comment by toobulkeh** [comment]
@dijonkitchen heads up -- Heroku enabled auto SSL support on the 21st - https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by croaky** [comment]
I like the general idea of Suspenders enforcing SSL out of the box. If `force_ssl = true` is the only config change, I say let's do it.

**Comment by toobulkeh** [comment]
I'll work on a PR

**Comment by croaky** [comment]
Opened https://github.com/thoughtbot/suspenders/pull/855 !
