### ISSUE TITLE
Could not find gem 'high_voltage' v1.40

### ISSUE THREAD

**Issue by jondkinney** [thoughtbot/suspenders#785]
In an effort to allow suspenders to still bootstrap new Rails 4 apps, I installed the last release that sticks with Rails 4.2.7 and was testing it out. I noticed the following in a fresh RVM ruby gemset after running `gem install suspenders -v1.40` and running `suspenders app_name`

```
    generate  suspenders:static
W, [2016-07-13T11:16:41.186035 #17526]  WARN -- : [SKYLIGHT] [0.10.5] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Running via Spring preloader in process 17529
     gemfile  high_voltage
    generate  suspenders:stylesheet_base
Could not find gem 'high_voltage' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
```

Perhaps high_voltage should be added as a development dependency so it gets installed when suspenders is gem installed?

**Comment by tute** [comment]
> Perhaps high_voltage should be added as a development dependency so it gets installed when suspenders is gem installed?

That would mean preinstalling any dependency the generators might use. What about running `bundle install` after Gemfile additions?

Thanks for your report!

**Comment by tute** [comment]
This was fixed as part of https://github.com/thoughtbot/suspenders/pull/790. Thanks for your report!
