### ISSUE TITLE
lists the gem refills (>= 0) more than once

### ISSUE THREAD

**Issue by secondstar** [thoughtbot/suspenders#786]
When I execute: 
`suspenders app --heroku true   --heroku-flags " --addons sendgrid,ssl"
`
all runs well except for this exception:

```
Your Gemfile lists the gem refills (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.

```

**Comment by tute** [comment]
This has been fixed in https://github.com/thoughtbot/suspenders/commit/f292096cfe1c77eeb253156664bc27fbfaecbb0b, soon to be released. Thanks for reporting!
