### ISSUE TITLE
Default scss setup for Bitters

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/suspenders#787]
It looks like the default generators create a standard setup, but the `*= require_tree .` sprockets directive needs to be replaced with the `@import`s that Bourbon likes. Any way this could happen on its own? May save folks like me some time trying to debug something that looks like this: https://github.com/thoughtbot/bitters/issues/234. (I thought I was having that same issue initially.)

**Comment by tute** [comment]
Thanks for your input, Loren! It looks like suspenders is not running by default the `suspenders:stylesheet_base` generator. This is a bug. Thank you again for reporting.

**Comment by tute** [comment]
The second application I generated (with gems already installed) did run the generator, fixing this issue. Failure lies in a middle step where a dependency is not met.

**Comment by tute** [comment]
Nailed it down:

```
...
     gemfile  high_voltage
    generate  suspenders:stylesheet_base
Could not find gem 'high_voltage' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
         run  bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Using rake 11.2.2
...
```
