### ISSUE TITLE
Missing turbolinks gem

### ISSUE THREAD

**Issue by lorentrogers** [thoughtbot/suspenders#788]
Seems like the application js file is sourcing turbolinks, but the gem is missing from the Gemfile. (I didn't have the turbolinks gem installed before, since this is a new machine.) Adding `gem "turbolinks"` fixed it for me locally -- not sure if this is something needed in Suspenders.

**Comment by tute** [comment]
Right. suspenders didn't include turbolinks for long (https://github.com/thoughtbot/suspenders/pull/225). @derekprior I know lately you've been using turbolinks with success. Should we revisit our stance on suspenders?

**Comment by tute** [comment]
Thanks for reporting, Loren!
