### ISSUE TITLE
New app fails with `Invalid null operation: "null gt null".`

### ISSUE THREAD

**Issue by MattMSumner** [thoughtbot/suspenders#797]
Here's an example app https://github.com/MattMSumner/test-sus-2.

Visiting http://localhost:3000/high_scores produces:

![screen shot 2016-09-16 at 10 22 43 am](https://cloud.githubusercontent.com/assets/759721/18589333/2b9178d2-7bf8-11e6-8576-8da144547eaf.png)

Commenting out https://github.com/MattMSumner/test-sus-2/blob/master/app/assets/stylesheets/base/_typography.scss#L15 "fixes" the issue.

**Comment by MattMSumner** [comment]
Seems like https://github.com/MattMSumner/test-sus-2 is working for other but https://github.com/MattMSumner/test-sus is an example where I've upgraded sprockets and this doesn't work. I get the following error:

![screen shot 2016-09-16 at 10 22 43 am](https://cloud.githubusercontent.com/assets/759721/18594960/79265320-7c10-11e6-9d35-b5c41dd088a3.png)

**Comment by tute** [comment]
Does this still happen on latest release? Thank you!

**Comment by tute** [comment]
cc @MattMSumner. Thank you!

**Comment by tute** [comment]
I assume #802 addressed this issue. Thanks!
