### ISSUE TITLE
Turbolinks is a high_voltage dependency but not in gemfile

### ISSUE THREAD

**Issue by shelmire** [thoughtbot/suspenders#808]
Turbolinks should be included in the gemfile by default.

**Comment by tute** [comment]
Why should it? Do you see an error? What were you expecting and what did you see? Thanks!

**Comment by shelmire** [comment]
Yes. If you create a static page under pages, such as when following the Bourbon tutorial on upcase, you get an error (after suspenders new, adding the static page).

This is the error: `ActionView::Template::Error (couldn't find file 'turbolinks' with type 'application/javascript'
Checked in these paths:` with a list of paths underneath.

Adding gem 'turbolinks' fixes the error.

**Comment by tute** [comment]
Thanks for the report. Would you please paste the full stacktrace as well? Thanks!

**Comment by tute** [comment]
@dgalarza do you think this bug belongs in high_voltage or is it suspenders'? Thank you!

**Comment by dgalarza** [comment]
There is no turbo links requirement within HighVoltage. I suspect something else is the cause of this.

**Comment by tute** [comment]
I just followed these steps and couldn't replicate your issue:

```
suspenders test-app
cd test-app
./bin/setup
rails g scaffold User email password
rake db:migrate
rails s
```

Verified `/users` works as expected. Then I created an `app/views/pages/about.html.erb` page, visited http://localhost:3000/pages/about, and everything worked as expected.

@shelmire how exactly can I see your error?

**Comment by shelmire** [comment]
I will try to replicate the issue and report back shortly; if I can't replicate it, I'll close the issue.

**Comment by shelmire** [comment]
Unable to replicate, I'm closing this.
