### ISSUE TITLE
Is neat gem supposed to be included?

### ISSUE THREAD

**Issue by RyanQuey** [thoughtbot/suspenders#816]
Neat is mentioned [here](https://github.com/thoughtbot/suspenders) as part of the suspenders set up, but it was not in the gem file when I installed suspenders, and it is not in the [gemfile](https://github.com/thoughtbot/suspenders/blob/master/templates/Gemfile.erb) either. It seems like there must be some mistake somewhere?

**Comment by tute** [comment]
It's added to the Gemfile as part of the generators:

```
lib/suspenders/generators/stylesheet_base_generator.rb
11:      gem "neat", "~> 2.0.0.beta.1"
```

It's tested in:

```
spec/features/new_project_spec.rb
260:  it "adds and configures bourbon, neat, and refills" do
264:    expect(gemfile).to match(/neat/)
268:  it "configures bourbon, neat, and refills" do
273:    expect(app_css).to match(/normalize-rails.*bourbon.*neat.*base.*refills/m)
```

Thanks!
