### ISSUE TITLE
triggering 'Error installing suspenders: suspenders requires Ruby version >= 2.4.0.'

### ISSUE THREAD

**Issue by mikesmayer** [thoughtbot/suspenders#830]
I'm using RBENV and running the latest version available which is ruby 2.4.0preview1 -- so not sure what to make of this error.

**Comment by odlp** [comment]
Hi @mikesmayer - you should be able to use Ruby `2.4.0` now.

Which versions do you see if you run:

```
ruby-build --definitions | grep ^2.4
```

On my machine I get:

```
2.4.0-dev
2.4.0-preview1
2.4.0-preview2
2.4.0-preview3
2.4.0-rc1
2.4.0
```

If you can't see the `2.4.0` definition you should be able to fetch get it by upgrading & installing:

```
brew upgrade rbenv ruby-build
rbenv install 2.4.0
```

**Comment by mikesmayer** [comment]
SOLVED: my ruby-build was out of date. seems brew upgrade wasn't sufficient.

```
cd ~/.rbenv/plugins/ruby-build
git pull

```
typing 'rbenv -l' was not listing the latest rubies:

```
  2.3.0
  2.3.1
  2.4.0-dev
  2.4.0-preview1
  jruby-1.5.6
  jruby-1.6.3
```
