### ISSUE TITLE
Move bin/setup_review_app to app.json for auto-setup

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#834]
Here's a [strategy](http://stackoverflow.com/a/36784098/1376201) for copying databases using `DATABASE_URL` env variable instead of requiring the Heroku API:

```js
// app.json
"scripts": {
  "postdeploy": "pg_dump $STAGING_DATABASE_URL | psql $DATABASE_URL && bundle exec rake db:migrate"
},
```

The downside of this is that it can cause problems if people use `app.json` for promoting apps to production from staging.

This would get rid of the step of typing `bin/setup_review_app ID` after every new PR.

**Comment by toobulkeh** [comment]
We might want to keep `bin/setup_review_app` depending on how people use it -- as [subsequent deploys don't](https://devcenter.heroku.com/articles/app-json-schema#scripts) run the `postdeploy` script from `app.json`

**Comment by toobulkeh** [comment]
@tute any thoughts on having this script only run on first deploy of PR env?

**Comment by tute** [comment]
That'd be killer. We shouldn't need to remember to manually run this script after each new PR.

But also, we maybe shouldn't be reusing the staging database, and use development seeds instead, per best practices and Heroku recommendation. That's probably another issue though.

**Comment by toobulkeh** [comment]
glad you like the concept! Just double-checking though -- is it a major problem or minor annoyance to not have this script run on every new deploy to an existing PR (branch and env)?

👍  on the concept of dev:prime > staging db. We try to practice that as well.

**Comment by tute** [comment]
It's a problem because otherwise there's no database. If you push the branch, and an owner runs acceptance, the app will fail with a "users table not found", or the like.

**Comment by toobulkeh** [comment]
Well -- this `app.json` script will run the first time the PR is created -- creating user tables.
it _won't_ run the second time (ie. someone pushes a fix to the same branch that the PR is based on.)

Sorry if I'm explaining something you already understand -- the language you're using just makes me think we're miscommunicating. 

For example, a scenario:

1. master branch is auto-deploying to the staging heroku environment
2. joe creates a new branch `phones` that adds a phone number column to the users table
3. he opens a PR (lets say 7) for `phones`
3. heroku automatically creates `staging-pr-7`
3. heroku automatically runs the `dev:prime` script and migrates the db, all via `app.json`
3. `staging-pr-7` is good to go and reflects phone numbers on users
3. joe's feature requirements expand to include a cell phone and a work phone number
3. joe adds a second phone number and features to support them
3. joe pushes those changes directly to `phones` since the PR hasn't been accepted
3. joe then needs to remember to run `rake/setup_review_app 7` to re-setup the PR branch

To me, this scenario is almost more awkward than the way things currently are (a major problem) because now there's 2 conditions to remember. I, as joe, only have to run rake/setup_review_app when it's my 2nd + push to each PR env.

On the other hand, some developers find this useful because most of the time they don't have to use `rake/setup_review_app 7` the first time.

Does that make sense?

https://devcenter.heroku.com/articles/app-json-schema#scripts

**Comment by toobulkeh** [comment]
Found another document that describes some other best-practices that are related, namely the `release` phase instead of the `postdeploy` phase of Heroku's build pipeline:

https://devcenter.heroku.com/articles/release-phase#getting-started

What we could probably do is use Procfile's `release` process to call `bin/release` which could then perform `bin/setup_review_app` if it's a PR environment:

```Procfile
release: bin/release
web: bundle exec puma -p $PORT -C ./config/puma.rb
worker: bundle exec rake jobs:work
```

```sh
# bin/release
#!/bin/sh

if [[ "$HEROKU_APP_NAME" == *"staging-pr-"* ]]; then
  bundle exec rake dev:prime #does create, migrate, and prime
else
  # whatever we want on staging and production apps
fi
```

One question remains -- is `dev:prime` or `db/seeds` _usually_ written to be re-runnable without a DB wipe?

**Comment by tute** [comment]
If step 5 happens automatically, then we are set! We just need the afterdeploy script configuration in there for this to run well.

As of now, step 5 does not run automatically for suspenders (unless I'm missing something), the database for `staging-pr-7` is not initialized, and so step 6 is expected but app is indeed not good to go as of yet. Today we run the script manually, but when we have step 5 in place, we won't need to.

Thanks for your time explaining this!

**Comment by toobulkeh** [comment]
You're correct.

What do you think of using my follow-up instead, the `release` phase? So that step 10 disappears too!

**Comment by tute** [comment]
Once the DB is setup, it stays like that on future commits.

I'd rather be able to push fixes without resetting the DB each time, and only reset it manually when asked for (or when it makes sense). I think that would be less surprising to people running acceptance.

**Comment by toobulkeh** [comment]
I think that can be solved with `db:migrate` on `release` and `dev:prime` on `postdeploy`.

Deal?

**Comment by tute** [comment]
I don't see the need of a release script. Anyhow, I'll leave the implementation details to suspenders' team! :)

**Comment by tute** [comment]
(And contributors like you!)

**Comment by toobulkeh** [comment]
Replaced by #859
