### ISSUE TITLE
Replace delayed_job with sidekiq?

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#836]
Heroku offers a free tier of redis which is used by sidekiq to offer fast ActiveJob support.

Sidekiq appears to be much more maintained / standardized than DelayedJob.

What do you think of this transition?
What about a plugin to offer a different solution choice?

Just curious about the discussion (since it hasn't been discussed publicly in this repo) and Rails 5.1 support is currently lacking in DJ (seems maintainers are lagging behind).

**Comment by eliotsykes** [comment]
DJ Rails 5.1 support is being worked on https://github.com/collectiveidea/delayed_job_active_record/pull/134

**Comment by nickcharlton** [comment]
It's a bit before my time, but my understanding is that DJ allows us to not have a dependency on Redis and that's helpful to keep.

Personally, I like Sidekiq a lot. But DJ seems to work fine (and we've replaced it on apps when something else is better). It looks like we'll be able to bump DJAR and have 5.1 support now, too.
