### ISSUE TITLE
Rails 5.2 & Credentials

### ISSUE THREAD

**Issue by toobulkeh** [thoughtbot/suspenders#838]
http://edgeguides.rubyonrails.org/5_1_release_notes.html

[Pull Request](https://github.com/rails/rails/pull/28038)

> Rails now allows management of application secrets in a secure way, building on top of the [sekrets](https://github.com/ahoward/sekrets) gem.
> Run `bin/rails secrets:setup` to setup a new encrypted secrets file. This will also generate a master key, which must be stored outside of the repository. The secrets themselves can then be safely checked into the revision control system, in an encrypted form.
> Secrets will be decrypted in production, using a key stored either in the `RAILS_MASTER_KEY` environment variable, or in a key file.

While this is great for passing around `.env` files and syncing problems @drapergeek has discussed / tried to automate, it's a bit more complex as it requires a deploy on ENV variable changes.

I'd suggest storing separate environments in separate files - and providing separate encryption keys per file - to maintain the same level of security of separate keys per env.

**Comment by toobulkeh** [comment]
There's a cool new "as a service" startup over at [ENVkey](https://www.envkey.com/) that solves this exact problem with single pane of glass management.

The problem with the service approach is this is a bit overkill for outside of the repository management... though it separates ENV keys very nicely (as opposed to the Rails secrets default that just manages secrets for production, I believe).

I'd love any input @tute or @croaky have

**Comment by croaky** [comment]
Injecting config via encrypted data is compelling. Doing some reading on the topic.

http://movingfast.io/articles/environment-variables-considered-harmful/

https://www.vaultproject.io/

**Comment by kigster** [comment]
And instead of secrets, which does not actually use proper encryption finctions, you should use https://GitHub.com/kigster/sym

**Comment by toobulkeh** [comment]
Here's a SaaS that focuses on solving this problem as well -- envkey.com

**Comment by purinkle** [comment]
This is a nice idea. I spent some time thinking about how it might work. I am not sure if it is viable as a change to Suspenders.

If we create our own custom solution to this, we still have the problem of storing private keys somewhere. We cannot store them in the repository because they would be available to everybody. This means we have to rely on a third-party service.

By relying on a third-party service, we are running into the same issues we have with third-party gems. Can we trust them with our secret environment variables? Also, using an external service for this seems overkill.

There is also the question of suitability for this utility. When you fire up a Rails app for the first time, do you expect it to take this level of security into account? Is it something we could somehow suggest to the developer rather than forcing it on them?

At the moment, I do not see how this fits into the Suspenders project. You could convince me, though.

**Comment by toobulkeh** [comment]
I agree on the 3rd party solution -- we've opted not to use it. We still would like to transition to shared encrypted keys though -- checked into the repo.

Is there the problem of encrypted keys with separate encryptions for each ENV?

**Comment by kigster** [comment]
With Sym gem, at least on Mac OSX you have an option of storing the keys in OSX Keychain.

**Comment by purinkle** [comment]
We could generate a local key for the generated application. The developer can then share the key amongst their team. If the developer needs to deploy to Heroku, we could store the key in the configuration variables. How does this sound?

**Comment by toobulkeh** [comment]
That's exactly what I had imagined -- and planned on using (it's the Rails encrypted_secrets model, correct?).

What do you think of @kigster's point to "proper encryption"? Is that worth using a separate gem instead of Rails defaults?

**Comment by kigster** [comment]
@toobulkeh Rails "default"? It's actually unheard of that Rails would announce "support for encryption" which is provided by an external gem — not Rails, while many solid alternatives exist! It's basically Rails "blessing", not Rails default. Not to mention they would do this without, seemingly, sanity-checking encryption routines.

**Comment by toobulkeh** [comment]
https://github.com/rails/rails/pull/28038 is in Rails 5.1, inspired by `sekrets` gem, but requires no external dependencies.

**Comment by kigster** [comment]
Thanks for the link! I'll read up and follow up here. In the meantime, feel free to use what suits you best. Thanks!

**Comment by purinkle** [comment]
Will [this new feature] coming in Rails 5.2 affect any work we do around this?

[this new feature]: http://weblog.rubyonrails.org/2017/9/23/this-week-in-rails-new-credentials-configuration-bugfixes-and-more/#introducing-configcredentialsymlenc-

**Comment by toobulkeh** [comment]
Good catch. Here's the merged PR from @dhh 
https://github.com/rails/rails/pull/30067

One major change is that this is done using a flat file instead of per env. This gets rid of the entire concept of development and test env variables, something that I'm not on board with. The whole advantage I'm looking for in encrypted_secrets (5.1, now deprecated in 5.2) was to pass around secrets without .env files.

**Comment by purinkle** [comment]
Looking at the merged PR, this might solve our problem.

The `config/credentials.yml.enc` would contain secrets for the Production environment. This would please our Staging and Production apps. It assumes we are happy for them to have the same secret key.

The implementation allows you to override any secrets by using `ENV`. Thus we could continue to set the secret keys for our Development and Test environments via a `.env` file.

This seems like a clean solution. Am I right? What are everybody else's feelings?

**Comment by toobulkeh** [comment]
I would prefer to have local dev variables encrypted as well -- as we often connect to external services that could be abused if leaked somehow... or else we would commit them to the repo today, right?

**Comment by toobulkeh** [comment]
We also still use different configs for things like S3 buckets and SMTP servers on staging and production, even though they're the same "production" Rack environment.

**Comment by jfelchner** [comment]
I'm in the process of updating the [Chamber Wiki](https://github.com/thekompanee/chamber/wiki) and releasing a new version which will allow different keypairs for each environment (falling back to a default).

Might be something you all want to take a look at.

**Comment by toobulkeh** [comment]
[Rails 5.2 now uses Credentials](https://github.com/rails/rails/pull/30067)

> In Rails 5.1, we added encrypted secrets. These secrets were like the old secrets but, uhm, more secret, because, you know, ENCRYPTION! Confusing? Yes. Why would you want secrets that weren’t really secret? Well, you don’t.
>In Rails 5.2, we’ve rectified the mess by deprecating the two different kinds of secrets and introduced a new shared concept called Credentials. Credentials, like AWS access keys and other forms of logins and passwords, were the dominant use case for secrets, so why not just call a spade a spade. So spade it is!
> Credentials are always encrypted. This means they’re safe to check into revision control, as long as you keep the key out of it. That means atomic deploys, no need to mess with a flurry of environment variables, and other benefits of having all credentials that the app needs in one place, safe and secure.

**Comment by composerinteralia** [comment]
Rails 6 has per-environment credentials: https://github.com/rails/rails/pull/33521

**Comment by stevepolitodesign** [comment]
Closing because the [latest release](https://github.com/thoughtbot/suspenders/releases/tag/v20240516.0) [requires Rails "~> 7.0"](https://github.com/thoughtbot/suspenders/blob/efe875c0810902766b836acc93f9a80b97f685dc/lib/suspenders/version.rb#L3). Additionally, the latest release uses as much as `rails new` as possible, which means we default to using Rails credentials.
