### ISSUE TITLE
Set ActionMailer's asset_host

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/suspenders#843]
We currently set the maiiler's `default_url_options` but not the `asset_host`. Because of this when you use the `_url` helpers in mailers it doesn't include the URL which is unexpected. 

We should probably update the config to also set `action_mailer.asset_host` to the environment's asset host which we already have.

Thoughts?

**Comment by nickcharlton** [comment]
We should do that. I'd happily merge such a PR!

**Comment by delphaber** [comment]
https://github.com/thoughtbot/suspenders/pull/853 !

**Comment by delphaber** [comment]
I've noticed I introduced a bug with that PR. Plus, we have to consider asset_host protocol. I'll open a new PR as soon as possibile

**Comment by purinkle** [comment]
@delphaber, is the original issue now dealt with by #853? Can we close this issue and open a new one for the bug that was introduced?

**Comment by delphaber** [comment]
@purinkle yes, it was introduced by #853. I already created a PR with the fix ( #858 ). But I have a question to ask you all. It's all in there :)
