### ISSUE TITLE
Use yarn for assets. PR welcome?

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#846]
Will you consider a pull request where `yarn` is used to load `normalize.css` instead of rails-assets?

**Comment by tute** [comment]
I think we should do this. `yarn` is now Rails default: http://weblog.rubyonrails.org/2017/4/27/Rails-5-1-final/

**Comment by nickcharlton** [comment]
As it is now the default, I'd not be against it.

I think I'd want to wait a little while to be introducing a new dependency though. Perhaps a few versions on from now?

**Comment by delphaber** [comment]
Nice! I'll do it!

**Comment by delphaber** [comment]
I've noticed we have to update rails first. I'll create a PR for rails 5.1 first :)

**Comment by delphaber** [comment]
Ok, I created a PR for Rails 5.1! https://github.com/thoughtbot/suspenders/pull/847

**Comment by antwonlee** [comment]
Yes!  Yarn!  Awesome!

**Comment by delphaber** [comment]
Here it is! https://github.com/thoughtbot/suspenders/pull/851

**Comment by nickcharlton** [comment]
Closing because of #851.
