### ISSUE TITLE
Decrease heroku slug size with .slugignore

### ISSUE THREAD

**Issue by delphaber** [thoughtbot/suspenders#854]
As written here https://devcenter.heroku.com/articles/slug-compiler#ignoring-files-with-slugignore we can reduce the heroku slug size (which limit is 500MB) with a `.slugignore` file.

I think it's a good idea to ignore `spec/` folders.

What do you think? Do you already use a `.slugignore`? Would you be interested in a PR?

**Comment by nickcharlton** [comment]
A `.slugignore` isn't something I've yet seen used. Can you give any examples where ignoring the specs makes a good difference the eventual slug size?

**Comment by delphaber** [comment]
We do not use heroku for every project, so it's my first time I heard about a `.slugignore`. I don't think `spec` folder will make a big difference as long as they are all text files, but I added the it because I read about it in the heroku article I linked before.

So I'm sorry but I do not have any real world example :(
I wanted to know if you ever used it and how.

You can close the issue :)

Thank for the feedback!

**Comment by croaky** [comment]
I've used `.slugignore` on a few projects such as thoughtbot.com. The biggest savings have been from other steps described in that Heroku article or https://robots.thoughtbot.com/how-to-reduce-a-large-heroku-compiled-slug-size

I could maybe see a benefit of having a `.sluginore` in a project that uses the `--heroku` flag as a way for teammates to discover more about slug maintenance but a fresh project shouldn't need it, is something that builds up later.

**Comment by nickcharlton** [comment]
Hmm, yeah, tb.com is a good example. I think I'm with @croaky on not seeing a need on a new project, so I'm going to close this issue for now.

Thank you though!
