### ISSUE TITLE
Circle 2.0 config

### ISSUE THREAD

**Issue by croaky** [thoughtbot/suspenders#865]
The current Circle config for Suspenders is Circle 1.0 config. 2.0 is a Docker-ized environment.

https://circleci.com/docs/2.0/faq/
https://circleci.com/docs/2.0/migrating-from-1-2/

**Comment by derekprior** [comment]
Also worth noting here that even under Circle 1.0, our configuration removes the benefit of automatic parallelization. If we leave the default test step, Circle will detect we want to use RSpec and use it's automatic parallelization strategy for RSpec, provided we have slots.

Fixing this or even trying to get the most out of Circle 2.0 likely means the end to "run exactly what CI runs just by running `rake`", right? We'd have to manually keep these in sync?

**Comment by mike-burns** [comment]
@croaky @derekprior do either of you want me to leave this issue open as a reminder? Or do you mind if I close it and we can continue the discussion on the PR?

**Comment by mike-burns** [comment]
We would need to change this one file: https://github.com/thoughtbot/suspenders/blob/master/lib/suspenders/generators/ci_generator.rb

**Comment by iwz** [comment]
@mike-burns, I think this is the file that needs to be updated: https://github.com/thoughtbot/suspenders/blob/master/templates/circle.yml.erb

**Comment by timup** [comment]
CircleCI 2.0 looks for configuration in a different location.  Will try to submit a PR with example config this weekend.  I have couple of suspenders based apps passing through 2.0, but not entirely happy with the setup.

**Comment by stevepolitodesign** [comment]
Closing in favor of #1135 and #1172.
