### ISSUE TITLE
Should rails_helper require spec_helper?

### ISSUE THREAD

**Issue by gylaz** [thoughtbot/suspenders#866]
Since `spec_helper` does a few best-practices, like block all external requests, should we require it in `rails_helper`?

**Comment by derekprior** [comment]
It is already required via rspec configuration (`--require spec_helper`) in `.rspec` but would it be helpful to be explicit?

**Comment by gylaz** [comment]
I just recently setup a new project with suspenders and didn't get a `.rspec` file at all. Is it something suspenders does or RSpec? Is there an additional RSpec install command that is expected to be ran? Is it possible latest versions of RSpec removed it?

**Comment by mike-burns** [comment]
I see a `.rspec` in the generated app:

```
~/thoughtbot/suspenders/tmp/dummy_app% cat .rspec 
--require spec_helper
```

Closing this; please reopen if you have more steps to reproduce this bug.
