### ISSUE TITLE
Heroku push is not getting the updated version of rubygems

### ISSUE THREAD

**Issue by shashankshandilyav** [thoughtbot/suspenders#890]
When pushing to heroku I am getting the following error 

> `suspenders-1.46.0 requires rubygems version >= 2.7.4, which is incompatible with

My current gem version is 2.7.4.

**Comment by mike-burns** [comment]
@shashankshandilyav 

Move `gem "suspenders"` to the `:development` group in your `Gemfile`, then re-run `bundle install`.

**Comment by mike-burns** [comment]
I've opened #891 as a clarifying bug report/TODO item for this. Thank you for reporting it.
