### ISSUE TITLE
Not able to push to heroku 

### ISSUE THREAD

**Issue by banavasi** [thoughtbot/suspenders#892]
remote: Compressing source files... done.
remote: Building source:
remote:
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:                         Detected buildpacks: Ruby,Node.js
remote:                         See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.5.0
remote: -----> Installing dependencies using bundler 1.15.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/.........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        Fetching rake 12.3.0
remote:        Fetching concurrent-ruby 1.0.5
remote:        Fetching minitest 5.11.3
remote:        Installing minitest 5.11.3
remote:        Installing concurrent-ruby 1.0.5
remote:        Installing rake 12.3.0
remote:        Fetching thread_safe 0.3.6
remote:        Installing thread_safe 0.3.6
remote:        Fetching builder 3.2.3
remote:        Installing builder 3.2.3
remote:        Fetching erubi 1.7.0
remote:        Fetching mini_portile2 2.3.0
remote:        Fetching crass 1.0.3
remote:        Installing erubi 1.7.0
remote:        Installing mini_portile2 2.3.0
remote:        Installing crass 1.0.3
remote:        Fetching rack 2.0.4
remote:        Fetching nio4r 2.2.0
remote:        Installing rack 2.0.4
remote:        Installing nio4r 2.2.0 with native extensions
remote:        Fetching websocket-extensions 0.1.3
remote:        Installing websocket-extensions 0.1.3
remote:        Fetching mini_mime 1.0.0
remote:        Installing mini_mime 1.0.0
remote:        Fetching arel 8.0.0
remote:        Installing arel 8.0.0
remote:        Fetching public_suffix 3.0.2
remote:        Fetching execjs 2.7.0
remote:        Installing execjs 2.7.0
remote:        Installing public_suffix 3.0.2
remote:        Fetching rb-fsevent 0.10.2
remote:        Installing rb-fsevent 0.10.2
remote:        Fetching ffi 1.9.21
remote:        Fetching thor 0.20.0
remote:        Installing thor 0.20.0
remote:        Installing ffi 1.9.21 with native extensions
remote:        Using bundler 1.15.2
remote:        Fetching flutie 2.0.0
remote:        Installing flutie 2.0.0
remote:        Fetching high_voltage 3.0.0
remote:        Installing high_voltage 3.0.0
remote:        Fetching honeybadger 3.3.0
remote:        Installing honeybadger 3.3.0
remote:        Fetching method_source 0.9.0
remote:        Installing method_source 0.9.0
remote:        Fetching pg 0.21.0
remote:        Installing pg 0.21.0 with native extensions
remote:        Fetching puma 3.11.2
remote:        Installing puma 3.11.2 with native extensions
remote:        Fetching rack-timeout 0.4.2
remote:        Installing rack-timeout 0.4.2
remote:        Fetching tilt 2.0.8
remote:        Installing tilt 2.0.8
remote:        Fetching i18n 0.9.5
remote:        Installing i18n 0.9.5
remote:        Fetching tzinfo 1.2.5
remote:        Installing tzinfo 1.2.5
remote:        Fetching nokogiri 1.8.2
remote:        Installing nokogiri 1.8.2 with native extensions
remote:        Fetching websocket-driver 0.6.5
remote:        Installing websocket-driver 0.6.5 with native extensions
remote:        Fetching mail 2.7.0
remote:        Installing mail 2.7.0
remote:        Fetching rack-test 0.8.2
remote:        Installing rack-test 0.8.2
remote:        Fetching sprockets 3.7.1
remote:        Installing sprockets 3.7.1
remote:        Fetching autoprefixer-rails 8.0.0
remote:        Installing autoprefixer-rails 8.0.0
remote:        Fetching uglifier 4.1.6
remote:        Installing uglifier 4.1.6
remote:        Fetching addressable 2.5.2
remote:        Installing addressable 2.5.2
remote:        Fetching rb-inotify 0.9.10
remote:        Installing rb-inotify 0.9.10
remote:        Fetching activesupport 5.1.5
remote:        Installing activesupport 5.1.5
remote:        Fetching recipient_interceptor 0.1.2
remote:        Installing recipient_interceptor 0.1.2
remote:        Fetching rack-canonical-host 0.2.3
remote:        Installing rack-canonical-host 0.2.3
remote:        Fetching sass-listen 4.0.0
remote:        Installing sass-listen 4.0.0
remote:        Fetching globalid 0.4.1
remote:        Installing globalid 0.4.1
remote:        Fetching activemodel 5.1.5
remote:        Installing activemodel 5.1.5
remote:        Fetching skylight 1.5.1
remote:        Installing skylight 1.5.1 with native extensions
remote:        Fetching sass 3.5.5
remote:        Installing sass 3.5.5
remote:        Fetching activejob 5.1.5
remote:        Installing activejob 5.1.5
remote:        Fetching activerecord 5.1.5
remote:        Installing activerecord 5.1.5
remote:        Fetching rails-dom-testing 2.0.3
remote:        Installing rails-dom-testing 2.0.3
remote:        Fetching loofah 2.2.0
remote:        Installing loofah 2.2.0
remote:        Fetching bourbon 5.0.0
remote:        Installing bourbon 5.0.0
remote:        Fetching neat 2.1.0
remote:        Installing neat 2.1.0
remote:        Fetching rails-html-sanitizer 1.0.3
remote:        Installing rails-html-sanitizer 1.0.3
remote:        Fetching actionview 5.1.5
remote:        Installing actionview 5.1.5
remote:        Fetching actionpack 5.1.5
remote:        Installing actionpack 5.1.5
remote:        Fetching actioncable 5.1.5
remote:        Fetching actionmailer 5.1.5
remote:        Installing actionmailer 5.1.5
remote:        Installing actioncable 5.1.5
remote:        Fetching railties 5.1.5
remote:        Fetching sprockets-rails 3.2.1
remote:        Installing sprockets-rails 3.2.1
remote:        Installing railties 5.1.5
remote:        Fetching jquery-rails 4.3.1
remote:        Fetching rails 5.1.5
remote:        Installing rails 5.1.5
remote:        Fetching sass-rails 5.0.7
remote:        Installing sass-rails 5.0.7
remote:        Installing jquery-rails 4.3.1
remote:        Fetching title 0.0.7
remote:        Installing title 0.0.7
remote:        Bundle complete! 38 Gemfile dependencies, 63 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (35.38s)
remote:        Cleaning up the bundler cache.
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        The latest bundler is 1.16.1, but you are currently running 1.15.2.
remote:        To update, run `gem install bundler`
remote: -----> Installing node-v6.11.1-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        KeyError: key not found: "SMTP_ADDRESS"
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/config/smtp.rb:2:in `fetch'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/config/smtp.rb:2:in `<top (required)>'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/config/environments/production.rb:1:in `<top (required)>'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/engine.rb:599:in `each'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/engine.rb:599:in `block in <class:Engine>'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:59:in `block in run_initializers'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:48:in `each'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:48:in `tsort_each_child'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/initializable.rb:58:in `run_initializers'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/application.rb:353:in `initialize!'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/config/environment.rb:2:in `<top (required)>'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/skylight-1.5.1/lib/skylight/probes.rb:81:in `require'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/application.rb:329:in `require_environment!'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/application.rb:445:in `block in run_tasks_blocks'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        /tmp/build_0f18d335c6df4f0481b9ff1f4d8f08bf/vendor/bundle/ruby/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to nischaya-staging.
remote:
To https://git.heroku.com/nischaya-staging.git
 ! [remote rejected] master -> master (pre-receive hook declined)

PS: I have configured my env variables in both heroku:set and unix shell

**Comment by bf4** [comment]
looks to me like

```
remote: KeyError: key not found: "SMTP_ADDRESS"
```

**Comment by shashankshandilyav** [comment]
Yes,  I am facing this issue I tried setting up my env variables in Heroku as well but no luck its failing in production build in the same place. Could someone suggest how you will configure env variables for this?

**Comment by bf4** [comment]
@shashankshandilyav to my eyes, you issue here has nothing to do with this repository, and is one of 1) reading the error message 2) learning how to configure heroku and perhaps 3) [describing what you've tried](http://www.benjaminfleischer.com/fragments/standard_responses/)

**Comment by toobulkeh** [comment]
@shashankshandilyav -- if you generated both environments (staging and production) using suspenders -- then `heroku:set` needs to be performed on both staging and production. By default, the `heroku:set` command is run against staging -- if you don't specify a heroku app via `--app` or remote via `--remote`.

I'd suggest using thoughtbot/parity, and instead of using heroku commands, you can use `staging <command>` and `production <command>`. This is a great pattern to use when working on a lot of projects (which is why it's the default recommended method -- as they're a consulting firm.

Hope this helps.

**Comment by stevepolitodesign** [comment]
Closing simply because the [latest release](https://github.com/thoughtbot/suspenders/releases/tag/v20240516.0) no longer assumes we default to hosting on Heroku.
