### ISSUE TITLE
Unable to create project with sqlite3 database

### ISSUE THREAD

**Issue by Yanchek99** [thoughtbot/suspenders#893]
When running `suspenders foobar --database sqlite3` I get the following error

```
Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```

**Comment by bf4** [comment]
Have you tried installing the sqlite3 gem?

**Comment by mattyancheksonos** [comment]
I have not, I was under the impression suspenders would load all required gems into the new projects gem file upon creation.  It seems there is actually a running list of prerequisite one needs before using this gem.

**Comment by thiagoa** [comment]
@Yanchek99 I know it's been some time, but thank you for reporting this issue! :heart:

I'm closing this ticket in favor of the following one:

https://github.com/thoughtbot/suspenders/issues/1082
