### ISSUE TITLE
Webpack support?

### ISSUE THREAD

**Issue by kbighorse** [thoughtbot/suspenders#904]
Would like to use Webpack instead of the asset pipeline, particularly with React:

https://github.com/rails/webpacker#react

**Comment by toobulkeh** [comment]
You can still use `--webpack=react` with suspenders, which just passes extra CLI arguments to Rails. Tested on 5.1.6.

**Comment by delphaber** [comment]
I think this issue could be closed :)

**Comment by composerinteralia** [comment]
Suspenders is now on Rails 6, which uses webpacker by default
