### ISSUE TITLE
Should javascript_include_tag be within <head> rather than <body>?

### ISSUE THREAD

**Issue by andyw8** [thoughtbot/suspenders#907]
I ran into the issue described here: ["jquery-ujs has already been loaded!" error]( https://stackoverflow.com/questions/20684846/turbolinks-causing-a-jquery-ujs-has-already-been-loaded-error)

It seems Suspenders is adding the `javascript_include_tag ` to the document `body` rather than `head`:

https://github.com/thoughtbot/suspenders/blob/master/templates/suspenders_layout.html.erb.erb
https://github.com/thoughtbot/suspenders/blob/master/templates/_javascript.html.erb

This is different from the current Rails default:

https://github.com/rails/rails/blob/552840660389e39f3ba8e47dcf35ab817c01cb48/activestorage/test/dummy/app/views/layouts/application.html.erb

**Comment by toobulkeh** [comment]
The issue you linked to was a 2012-2014 problem with Turbolinks conflicting with UJS.

With all external files, the page is processed (and pulls external files) in their order on the DOM. So it's good practice to move things not required for above-the-fold rendering to the end of the body. With the advent of HTTP2 (still not completely supported everywhere), a browser can request more than one file from the same HTTP link -- so this matters less.

What still matters is if the script is processed before rendering items in the DOM, which still happens unless you use async.

As for why Rails doesn't do this -- it probably has to do with them still using turbolinks, and the problems turbolinks causes.

All of this is what I've learned, and have not run benchmarks or anything, so YMMV.

**Comment by mike-burns** [comment]
Closing this because toobulkeh gave the answer I would give, but with really nice wording.
