### ISSUE TITLE
Generators fail if certain gems aren't already installed

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/suspenders#910]
If `bullet`, `capybara-webkit`, and `factory_bot_rails` are not already installed before generating a new app, several of the generators fail with bundler errors like `"Could not find gem 'bullet' in any of the gem sources listed in your Gemfile."`

Steps to reproduce:

```
gem uninstall bullet capybara-webkit factory_bot_rails
suspenders test_app
```

**Comment by toobulkeh** [comment]
this breaks entire builds, as the entire suspenders:factories generator doesn't run, missing the generation of the dev:prime task, which breaks bin/setup. 🐢all the way down.

**Comment by spenser-loanlink** [comment]
This still seems to be an issue, specifically if capybara-webkit isn't in the gemfile.

**Comment by composerinteralia** [comment]
We swapped out `capybara-webkit` in https://github.com/thoughtbot/suspenders/commit/cf78134766c689dab1d9e5db2f3be454ba81f487

**Comment by bananatron** [comment]
@composerinteralia I'm so confused - if you generate a new app with v1.47 `capybara-webkit` IS in the gemfile. I must be totally missing something here?

**Comment by composerinteralia** [comment]
Yeah, sorry for that vague comment. I do think the problem will go away with the next release.
