### ISSUE TITLE
Shouldn't .env be in the .gitignore?

### ISSUE THREAD

**Issue by benfurber** [thoughtbot/suspenders#922]
The git ignore file has ```/.env.local``` but that hasn't covered ```.env``` [which has been added to my Github cloned repo](https://github.com/benfurber/suspenders_playing). Lucky I hadn't added anything to it.

This should be added right? Happy to do the pr if so. And equally would love to know why I'm wrong if not(!) 

Thanks.

**Comment by toobulkeh** [comment]
https://github.com/thoughtbot/suspenders/commit/8739344046cfbca5b74dcb4d9aba3c6e9c805463

**Comment by delphaber** [comment]
I think this issue can be closed :)
