### ISSUE TITLE
Even when using latest suspenders, I still run into Rack::Timeout

### ISSUE THREAD

**Issue by desireco** [thoughtbot/suspenders#927]
I see pull req that fixes the issue, yet even with latest suspenders, newly create app, which creates heroku environments still can't be deployed. After env variables are set for SMTP, I am still getting 

NoMethodError: undefined method `timeout=' for Rack::Timeout:Class

I tried setting RACK_TIMEOUT_SERVICE_TIMEOUT=10 on staging, but it doesn't seem to help.

Am I doing something wrong or missing a step. Appreciate help on this.

**Comment by rikkipitt** [comment]
@desireco You need to remove `Rack::Timeout.timeout = (ENV["RACK_TIMEOUT"] || 10).to_i` from the bottom of your config/environments/production.rb file

**Comment by desireco** [comment]
Ahh, makes sense :) Thank you.

**Comment by toobulkeh** [comment]
this is repaired by https://github.com/thoughtbot/suspenders/pull/920

@croaky can we get a new version cut?
