### ISSUE TITLE
Heroku deployment issues

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/suspenders#930]
Thanks to @keiranking for taking great notes while he tried to deploy his first Rails app to Heroku:

---

# Trying to deploy Suspenders app to Heroku

- Ran:
  + `heroku login`
  + `heroku create`
  + `git push heroku master`

- Build failed, solved by creating environment variables on Heroku
  + ASSET_HOST: siteURL.herokuapp.com
  + APPLICATION_HOST: siteURL.herokuapp.com
  + SMTP_ADDRESS: 'smtp.example.com'
  + SMTP_DOMAIN: 'example.com'
  + SMTP_USERNAME: 'username'
  + SMTP_PASSWORD: 'password'

- Build failed, `Undefined method 'timeout' error`, solved by deleting obsolete Rack::Timeout.timeout call in `config/environments/production.rb`
  https://github.com/thoughtbot/desks/commit/db3ebed816d41fe901ff8b08312a19e12111bc09

- Build failed, solved by:
  + adding `gem "webpacker", require: false` to Gemfile
  + running `bundle exec rails webpacker:install` (not sure if was necessary)
  https://github.com/rails/webpacker

- Build failed, conflict between `package-lock.json` and `yarn.lock`, solved by removing `package-lock.json`

- Build failed, solved by adding the following buildpacks on Heroku Dashboard > Settings > Buildpacks:
  + heroku/nodejs
  + heroku/ruby

- Build succeeded, but `bundler: failed to load command: puma`, solved by adding Heroku Postgres on Heroku Dashboard > Resources > Add-ons

- Build succeeded, site failed to load, solved by running `heroku run rake db:migrate`

**Comment by mike-burns** [comment]
> Build succeeded, site failed to load, solved by running `heroku run rake db:migrate`

https://github.com/thoughtbot/suspenders/pull/937
https://github.com/thoughtbot/suspenders/pull/906

> Build failed, Undefined method 'timeout' error, solved by deleting obsolete Rack::Timeout.timeout call in config/environments/production.rb

Fixed in 59357600b0dec1729a012f24a3fdd426cc3198b5.

**Comment by RossKinsella** [comment]
Another item I had to do was to ensure my gemlock was bundled with bundler < 2.0 and also remove the bundler 2 buildpack from heroku
