### ISSUE TITLE
Set up for heroku after app creation?

### ISSUE THREAD

**Issue by ZASMan** [thoughtbot/suspenders#935]
Hi, in your readme it says to run `suspenders app --heroku true` on creation to set up an app easier for Heroku. However, I didn't do that when I started up a suspenders application, and now get the error `       KeyError: key not found: "SMTP_ADDRESS"` when I try to deploy manually from the Heroku site. I'm wondering if it has something to do with not configuring it on startup? Thank you!

**Comment by vcavallo** [comment]
@ZASMan See #930

**Comment by bhtabor** [comment]
```
#First check ENV variables you need from config/environments/production.rb
#You need at least APPLICATION_HOST
heroku config:set APPLICATION_HOST=your-app.herokuapp.com

#Then add node for yarn install, skip if you have 'gem "webpacker", require: false' in Gemfile
heroku buildpacks:set heroku/ruby
heroku buildpacks:add --index 1 heroku/nodejs

#Then push to your heroku git remote, default - heroku, and run db migration
git push herku master
heroku run rails db:migrate

```

**Comment by thiagoa** [comment]
Closing this ticket because we already have this one to deal with Heroku issues:

https://github.com/thoughtbot/suspenders/issues/930

Thank you @ZASMan for opening it ❤️
