### ISSUE TITLE
Keep action mailer config together

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/suspenders#946]
https://github.com/thoughtbot/suspenders/blob/285c002cb1095a0031444840b8ee1c31324264e8/lib/suspenders/actions.rb#L12..L28 adds action_mailer configuration to the end of the file, whereas https://github.com/thoughtbot/suspenders/blob/285c002cb1095a0031444840b8ee1c31324264e8/lib/suspenders/generators/production/email_generator.rb#L21..L30 adds action_mailer configuration below some other action_mailer configuration. It might be nice to keep related configuration grouped together.

**Comment by stevepolitodesign** [comment]
Closed by #1162
