### ISSUE TITLE
Honeybadger API Key

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/suspenders#949]
The Readme states that I should add a "HONEYBADGER_ENV" variable. However, the Honeybadger documentation states that I should a different variable "HONEYBADGER_API_KEY".

    https://docs.honeybadger.io/ruby/integration-guides/rails-exception-tracking.html

**Comment by composerinteralia** [comment]
Thanks for the issue. 😸 

The README mentions that the `--heroku true` flag:

> Configures staging with HONEYBADGER_ENV environment variable set to staging

`HONEYBADGER_ENV` allows you to [configure the environment that gets passed to honeybadger](https://docs.honeybadger.io/lib/ruby/getting-started/environments.html). It is separate from the `HONEYBADGER_API_KEY`, which you will need to add manually when setting up honeybadger.
