### ISSUE TITLE
Doesn't seem to work as of the release of bundler 2.0

### ISSUE THREAD

**Issue by sosodev** [thoughtbot/suspenders#958]
Fresh Ruby 2.5.3 install following the instructions
`gem install suspenders`
`suspenders projectname`
fails because the bundler requirement can't be satisfied given the gems in the gemfile

**Comment by composerinteralia** [comment]
This is probably related to https://github.com/rubysec/bundler-audit/issues/202

**Comment by composerinteralia** [comment]
It looks like this has sorted itself out so I am going to close the issue. Thanks!
