### ISSUE TITLE
[Feature] Rails 6 config.hosts

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/suspenders#975]
I don't understand this yet but [Rails 6 will be introducing an `ActionDispatch::HostAuthorization` middleware](https://medium.com/rubyinside/whats-coming-to-rails-6-0-8ec79eea66da#831a) that automatically configures itself. A quick search indicates that [it configures itself via the `config.hosts` value](https://github.com/rails/rails/blob/528c5bb224a2f9ea6eee7b15ef5de5e9d17bf309/railties/lib/rails/application/default_middleware_stack.rb#L16).

We should probably find a way to set that.

**Comment by stevepolitodesign** [comment]
The [latest release](https://github.com/thoughtbot/suspenders/releases/tag/v20240516.0) made the decision to rely on as much of `rails new` as possible. Although we make some recommendations via the following configuration generators, we ultimately decided to leave infrastructure decisions up to the consumer.

- #1151
- #1149
-  #1182

[This](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization) his how it can be configured.

**Comment by mike-burns** [comment]
Thanks for that redesign!
