### ISSUE TITLE
Use pre-registered headless Chrome in Capybara

### ISSUE THREAD

**Issue by StevenXL** [thoughtbot/suspenders#988]
Hello - this is more of a question than an issue (please correct me if this is the wrong place to ask), but I was wondering why the `suspenders` scaffold registers a new javascript driver for headless Chrome, when the driver [:selenium_chrome_headless](https://github.com/teamcapybara/capybara/blob/3.28_stable/lib/capybara/registrations/drivers.rb) is pre-registered in capybara.

**Comment by composerinteralia** [comment]
I don't know the full history (you could try looking through `git blame` to see why things were added when they were), but if we could remove code from suspenders and still get the same effect I would support that.
