### ISSUE TITLE
Fix headless system test setup

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/suspenders#994]
To get system tests running headless I have needed to replace:

```rb
Capybara.javascript_driver = :headless_chrome
```

with:

```rb
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :headless_chrome
  end
end
```

We should also replace `chromedriver-helper` with `webdrivers`, since chromedriver-helper is deprecated

**Comment by mike-burns** [comment]
Fixed in #1010 .
